// Generated by commsdsl2tools_qt v6.3.4

#pragma once

#include <tuple>
#include <QtCore/QVariantList>
#include "cc_tools_qt/TransportMessageBase.h"
#include "cc_tools_qt_plugin/cc_ublox/options/DefaultOptions.h"
#include "cc_ublox/frame/UbloxFrame.h"
#include "cc_tools_qt_plugin/cc_ublox/Message.h"

namespace cc_tools_qt_plugin
{

namespace cc_ublox
{

namespace frame
{

struct UbloxFrameTransportMessageFields
{
    using All =
        std::tuple<
            ::cc_ublox::frame::UbloxFrameLayers<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::SyncMembers::Sync,
            ::cc_ublox::frame::UbloxFrameLayers<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::IdMembers::MsgId,
            ::cc_ublox::frame::UbloxFrameLayers<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::LengthMembers::LENGTH,
            ::cc_ublox::frame::UbloxFrameLayers<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Payload::Field,
            ::cc_ublox::frame::UbloxFrameLayers<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::ChecksumMembers::Checksum
        >;
    static const QVariantList& props();
};

class UbloxFrameTransportMessage : public
    cc_tools_qt::TransportMessageBase<
        cc_tools_qt_plugin::cc_ublox::Message,
        UbloxFrameTransportMessageFields::All
    >
{
protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override;
    virtual comms::ErrorStatus readImpl(ReadIterator& iter, std::size_t len) override;
};

} // namespace frame

} // namespace cc_ublox

} // namespace cc_tools_qt_plugin
