// Generated by commsdsl2tools_qt v6.3.2

#pragma once

#include <tuple>
#include "cc_tools_qt_plugin/cc_ublox/message/AckAck.h"
#include "cc_tools_qt_plugin/cc_ublox/message/AckNak.h"
#include "cc_tools_qt_plugin/cc_ublox/message/AidAlm.h"
#include "cc_tools_qt_plugin/cc_ublox/message/AidAlmPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/AidAlmPollSv.h"
#include "cc_tools_qt_plugin/cc_ublox/message/AidAlp.h"
#include "cc_tools_qt_plugin/cc_ublox/message/AidAlpData.h"
#include "cc_tools_qt_plugin/cc_ublox/message/AidAlpStatus.h"
#include "cc_tools_qt_plugin/cc_ublox/message/AidAlpsrv.h"
#include "cc_tools_qt_plugin/cc_ublox/message/AidAlpsrvToServer.h"
#include "cc_tools_qt_plugin/cc_ublox/message/AidAop.h"
#include "cc_tools_qt_plugin/cc_ublox/message/AidAopPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/AidAopPollSv.h"
#include "cc_tools_qt_plugin/cc_ublox/message/AidAopU8.h"
#include "cc_tools_qt_plugin/cc_ublox/message/AidData.h"
#include "cc_tools_qt_plugin/cc_ublox/message/AidEph.h"
#include "cc_tools_qt_plugin/cc_ublox/message/AidEphPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/AidEphPollSv.h"
#include "cc_tools_qt_plugin/cc_ublox/message/AidHui.h"
#include "cc_tools_qt_plugin/cc_ublox/message/AidHuiPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/AidIni.h"
#include "cc_tools_qt_plugin/cc_ublox/message/AidIniPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/AidReq.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgAnt.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgAntPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgCfg.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgDat.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgDatPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgDatStandard.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgDatUser.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgDgnss.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgDgnssPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgDosc.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgDoscPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgEkf.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgEkfPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgEsrc.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgEsrcPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgFixseed.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgFxn.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgFxnPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgGeofence.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgGeofencePoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgGnss.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgGnssPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgHnr.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgHnrPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgInf.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgInfPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgItfm.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgItfmPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgLogfilter.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgLogfilterPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgMsg.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgMsgCurrent.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgMsgPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgNav5.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgNav5Poll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgNavx5.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgNavx5Poll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgNavx5V2.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgNavx5V3.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgNmea.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgNmeaPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgNmeaV0.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgNmeaV1.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgNvs.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgOdo.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgOdoPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgPm.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgPm2.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgPm2Poll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgPm2V2.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgPmPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgPms.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgPmsPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgPrtDdc.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgPrtPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgPrtPortPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgPrtSpi.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgPrtUart.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgPrtUsb.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgPwr.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgRate.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgRatePoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgRinv.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgRinvPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgRst.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgRxm.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgRxmPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgSbas.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgSbasPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgSmgr.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgSmgrPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgTmode.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgTmode2.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgTmode2Poll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgTmode3.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgTmode3Poll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgTmodePoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgTp.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgTp5.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgTp5Poll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgTp5PollSelect.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgTpPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgTxslot.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgUsb.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgUsbPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgValdel.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgValget.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgValgetPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/CfgValset.h"
#include "cc_tools_qt_plugin/cc_ublox/message/EsfIns.h"
#include "cc_tools_qt_plugin/cc_ublox/message/EsfInsPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/EsfMeas.h"
#include "cc_tools_qt_plugin/cc_ublox/message/EsfMeasPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/EsfRaw.h"
#include "cc_tools_qt_plugin/cc_ublox/message/EsfStatus.h"
#include "cc_tools_qt_plugin/cc_ublox/message/EsfStatusPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/HnrPvt.h"
#include "cc_tools_qt_plugin/cc_ublox/message/HnrPvtPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/InfDebug.h"
#include "cc_tools_qt_plugin/cc_ublox/message/InfError.h"
#include "cc_tools_qt_plugin/cc_ublox/message/InfNotice.h"
#include "cc_tools_qt_plugin/cc_ublox/message/InfTest.h"
#include "cc_tools_qt_plugin/cc_ublox/message/InfWarning.h"
#include "cc_tools_qt_plugin/cc_ublox/message/LogBatch.h"
#include "cc_tools_qt_plugin/cc_ublox/message/LogCreate.h"
#include "cc_tools_qt_plugin/cc_ublox/message/LogErase.h"
#include "cc_tools_qt_plugin/cc_ublox/message/LogFindtime.h"
#include "cc_tools_qt_plugin/cc_ublox/message/LogFindtimeResp.h"
#include "cc_tools_qt_plugin/cc_ublox/message/LogInfo.h"
#include "cc_tools_qt_plugin/cc_ublox/message/LogInfoPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/LogRetrieve.h"
#include "cc_tools_qt_plugin/cc_ublox/message/LogRetrievebatch.h"
#include "cc_tools_qt_plugin/cc_ublox/message/LogRetrievepos.h"
#include "cc_tools_qt_plugin/cc_ublox/message/LogRetrieveposextra.h"
#include "cc_tools_qt_plugin/cc_ublox/message/LogRetrievestring.h"
#include "cc_tools_qt_plugin/cc_ublox/message/LogString.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaAck.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaAno.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaBdsAlm.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaBdsEph.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaBdsHealth.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaBdsIono.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaBdsUtc.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaDbd.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaDbdPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaFlashAck.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaFlashEph.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaFlashStop.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaGalAlm.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaGalEph.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaGalTimeoffset.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaGalUtc.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaGloAlm.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaGloEph.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaGloTimeoffset.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaGpsAlm.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaGpsEph.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaGpsHealth.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaGpsIono.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaGpsUtc.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaIniClkd.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaIniEop.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaIniFreq.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaIniPosLlh.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaIniPosXyz.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaIniTimeGnss.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaIniTimeUtc.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaQzssAlm.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaQzssEph.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MgaQzssHealth.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonComms.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonCommsPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonGnss.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonGnssPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonHw.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonHw2.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonHw2Poll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonHw3.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonHw3Poll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonHwPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonIo.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonIoPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonMsgpp.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonMsgppPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonPatch.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonPatchPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonRf.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonRfPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonRxbuf.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonRxbufPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonRxr.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonSmgr.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonSmgrPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonSpan.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonSpanPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonTxbuf.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonTxbufPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonVer.h"
#include "cc_tools_qt_plugin/cc_ublox/message/MonVerPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavAopstatus.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavAopstatusPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavAopstatusUblox8.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavAtt.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavAttPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavClock.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavClockPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavDgps.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavDgpsPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavDop.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavDopPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavEoe.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavGeofence.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavGeofencePoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavHpposecef.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavHpposecefPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavHpposllh.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavHpposllhPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavOdo.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavOdoPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavOrb.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavOrbPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavPosecef.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavPosecefPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavPosllh.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavPosllhPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavPvt.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavPvtPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavPvt_u8.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavRelposned.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavRelposnedPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavRelposned_v1.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavResetodo.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavSat.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavSatPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavSbas.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavSbasPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavSig.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavSigPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavSlas.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavSlasPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavSol.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavSolPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavStatus.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavStatusPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavSvin.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavSvinPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavSvinfo.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavSvinfoPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavTimebds.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavTimebdsPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavTimegal.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavTimegalPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavTimeglo.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavTimegloPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavTimegps.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavTimegpsPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavTimels.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavTimelsPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavTimeutc.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavTimeutcPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavVelecef.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavVelecefPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavVelned.h"
#include "cc_tools_qt_plugin/cc_ublox/message/NavVelnedPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/RxmAlm.h"
#include "cc_tools_qt_plugin/cc_ublox/message/RxmAlmPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/RxmAlmPollSv.h"
#include "cc_tools_qt_plugin/cc_ublox/message/RxmEph.h"
#include "cc_tools_qt_plugin/cc_ublox/message/RxmEphPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/RxmEphPollSv.h"
#include "cc_tools_qt_plugin/cc_ublox/message/RxmImes.h"
#include "cc_tools_qt_plugin/cc_ublox/message/RxmImesPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/RxmMeasx.h"
#include "cc_tools_qt_plugin/cc_ublox/message/RxmPmreq.h"
#include "cc_tools_qt_plugin/cc_ublox/message/RxmPmreqV0.h"
#include "cc_tools_qt_plugin/cc_ublox/message/RxmRaw.h"
#include "cc_tools_qt_plugin/cc_ublox/message/RxmRawPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/RxmRawx.h"
#include "cc_tools_qt_plugin/cc_ublox/message/RxmRawxPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/RxmRlmLong.h"
#include "cc_tools_qt_plugin/cc_ublox/message/RxmRlmShort.h"
#include "cc_tools_qt_plugin/cc_ublox/message/RxmRtcm.h"
#include "cc_tools_qt_plugin/cc_ublox/message/RxmSfrb.h"
#include "cc_tools_qt_plugin/cc_ublox/message/RxmSfrbx.h"
#include "cc_tools_qt_plugin/cc_ublox/message/RxmSvsi.h"
#include "cc_tools_qt_plugin/cc_ublox/message/RxmSvsiPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/SecSign.h"
#include "cc_tools_qt_plugin/cc_ublox/message/SecUniqid.h"
#include "cc_tools_qt_plugin/cc_ublox/message/SecUniqidPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/TimDosc.h"
#include "cc_tools_qt_plugin/cc_ublox/message/TimFchg.h"
#include "cc_tools_qt_plugin/cc_ublox/message/TimFchgPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/TimSmeas.h"
#include "cc_tools_qt_plugin/cc_ublox/message/TimSvin.h"
#include "cc_tools_qt_plugin/cc_ublox/message/TimSvinPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/TimTm2.h"
#include "cc_tools_qt_plugin/cc_ublox/message/TimTm2Poll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/TimTos.h"
#include "cc_tools_qt_plugin/cc_ublox/message/TimTp.h"
#include "cc_tools_qt_plugin/cc_ublox/message/TimTpPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/TimVcocal.h"
#include "cc_tools_qt_plugin/cc_ublox/message/TimVcocalExt.h"
#include "cc_tools_qt_plugin/cc_ublox/message/TimVcocalPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/TimVcocalStop.h"
#include "cc_tools_qt_plugin/cc_ublox/message/TimVrfy.h"
#include "cc_tools_qt_plugin/cc_ublox/message/TimVrfyPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/UpdSosAck.h"
#include "cc_tools_qt_plugin/cc_ublox/message/UpdSosClear.h"
#include "cc_tools_qt_plugin/cc_ublox/message/UpdSosCreate.h"
#include "cc_tools_qt_plugin/cc_ublox/message/UpdSosPoll.h"
#include "cc_tools_qt_plugin/cc_ublox/message/UpdSosRestored.h"

namespace cc_tools_qt_plugin
{

namespace cc_ublox
{

namespace input
{

using AllMessages =
    std::tuple<
        cc_tools_qt_plugin::cc_ublox::message::NavPosecef,
        cc_tools_qt_plugin::cc_ublox::message::NavPosecefPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavPosllh,
        cc_tools_qt_plugin::cc_ublox::message::NavPosllhPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavStatus,
        cc_tools_qt_plugin::cc_ublox::message::NavStatusPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavDop,
        cc_tools_qt_plugin::cc_ublox::message::NavDopPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavAtt,
        cc_tools_qt_plugin::cc_ublox::message::NavAttPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavSol,
        cc_tools_qt_plugin::cc_ublox::message::NavSolPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavPvt_u8,
        cc_tools_qt_plugin::cc_ublox::message::NavPvt,
        cc_tools_qt_plugin::cc_ublox::message::NavPvtPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavOdo,
        cc_tools_qt_plugin::cc_ublox::message::NavOdoPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavResetodo,
        cc_tools_qt_plugin::cc_ublox::message::NavVelecef,
        cc_tools_qt_plugin::cc_ublox::message::NavVelecefPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavVelned,
        cc_tools_qt_plugin::cc_ublox::message::NavVelnedPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavHpposecef,
        cc_tools_qt_plugin::cc_ublox::message::NavHpposecefPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavHpposllh,
        cc_tools_qt_plugin::cc_ublox::message::NavHpposllhPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavTimegps,
        cc_tools_qt_plugin::cc_ublox::message::NavTimegpsPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavTimeutc,
        cc_tools_qt_plugin::cc_ublox::message::NavTimeutcPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavClock,
        cc_tools_qt_plugin::cc_ublox::message::NavClockPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavTimeglo,
        cc_tools_qt_plugin::cc_ublox::message::NavTimegloPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavTimebds,
        cc_tools_qt_plugin::cc_ublox::message::NavTimebdsPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavTimegal,
        cc_tools_qt_plugin::cc_ublox::message::NavTimegalPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavTimels,
        cc_tools_qt_plugin::cc_ublox::message::NavTimelsPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavSvinfo,
        cc_tools_qt_plugin::cc_ublox::message::NavSvinfoPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavDgps,
        cc_tools_qt_plugin::cc_ublox::message::NavDgpsPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavSbas,
        cc_tools_qt_plugin::cc_ublox::message::NavSbasPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavOrb,
        cc_tools_qt_plugin::cc_ublox::message::NavOrbPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavSat,
        cc_tools_qt_plugin::cc_ublox::message::NavSatPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavGeofence,
        cc_tools_qt_plugin::cc_ublox::message::NavGeofencePoll,
        cc_tools_qt_plugin::cc_ublox::message::NavSvin,
        cc_tools_qt_plugin::cc_ublox::message::NavSvinPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavRelposned_v1,
        cc_tools_qt_plugin::cc_ublox::message::NavRelposned,
        cc_tools_qt_plugin::cc_ublox::message::NavRelposnedPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavSlas,
        cc_tools_qt_plugin::cc_ublox::message::NavSlasPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavSig,
        cc_tools_qt_plugin::cc_ublox::message::NavSigPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavAopstatus,
        cc_tools_qt_plugin::cc_ublox::message::NavAopstatusUblox8,
        cc_tools_qt_plugin::cc_ublox::message::NavAopstatusPoll,
        cc_tools_qt_plugin::cc_ublox::message::NavEoe,
        cc_tools_qt_plugin::cc_ublox::message::RxmRaw,
        cc_tools_qt_plugin::cc_ublox::message::RxmRawPoll,
        cc_tools_qt_plugin::cc_ublox::message::RxmSfrb,
        cc_tools_qt_plugin::cc_ublox::message::RxmSfrbx,
        cc_tools_qt_plugin::cc_ublox::message::RxmMeasx,
        cc_tools_qt_plugin::cc_ublox::message::RxmRawx,
        cc_tools_qt_plugin::cc_ublox::message::RxmRawxPoll,
        cc_tools_qt_plugin::cc_ublox::message::RxmSvsi,
        cc_tools_qt_plugin::cc_ublox::message::RxmSvsiPoll,
        cc_tools_qt_plugin::cc_ublox::message::RxmAlm,
        cc_tools_qt_plugin::cc_ublox::message::RxmAlmPollSv,
        cc_tools_qt_plugin::cc_ublox::message::RxmAlmPoll,
        cc_tools_qt_plugin::cc_ublox::message::RxmEph,
        cc_tools_qt_plugin::cc_ublox::message::RxmEphPollSv,
        cc_tools_qt_plugin::cc_ublox::message::RxmEphPoll,
        cc_tools_qt_plugin::cc_ublox::message::RxmRtcm,
        cc_tools_qt_plugin::cc_ublox::message::RxmPmreqV0,
        cc_tools_qt_plugin::cc_ublox::message::RxmPmreq,
        cc_tools_qt_plugin::cc_ublox::message::RxmRlmLong,
        cc_tools_qt_plugin::cc_ublox::message::RxmRlmShort,
        cc_tools_qt_plugin::cc_ublox::message::RxmImes,
        cc_tools_qt_plugin::cc_ublox::message::RxmImesPoll,
        cc_tools_qt_plugin::cc_ublox::message::InfError,
        cc_tools_qt_plugin::cc_ublox::message::InfWarning,
        cc_tools_qt_plugin::cc_ublox::message::InfNotice,
        cc_tools_qt_plugin::cc_ublox::message::InfTest,
        cc_tools_qt_plugin::cc_ublox::message::InfDebug,
        cc_tools_qt_plugin::cc_ublox::message::AckNak,
        cc_tools_qt_plugin::cc_ublox::message::AckAck,
        cc_tools_qt_plugin::cc_ublox::message::CfgPrtDdc,
        cc_tools_qt_plugin::cc_ublox::message::CfgPrtUart,
        cc_tools_qt_plugin::cc_ublox::message::CfgPrtUsb,
        cc_tools_qt_plugin::cc_ublox::message::CfgPrtSpi,
        cc_tools_qt_plugin::cc_ublox::message::CfgPrtPortPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgPrtPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgMsg,
        cc_tools_qt_plugin::cc_ublox::message::CfgMsgCurrent,
        cc_tools_qt_plugin::cc_ublox::message::CfgMsgPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgInf,
        cc_tools_qt_plugin::cc_ublox::message::CfgInfPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgRst,
        cc_tools_qt_plugin::cc_ublox::message::CfgDat,
        cc_tools_qt_plugin::cc_ublox::message::CfgDatUser,
        cc_tools_qt_plugin::cc_ublox::message::CfgDatStandard,
        cc_tools_qt_plugin::cc_ublox::message::CfgDatPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgTp,
        cc_tools_qt_plugin::cc_ublox::message::CfgTpPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgRate,
        cc_tools_qt_plugin::cc_ublox::message::CfgRatePoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgCfg,
        cc_tools_qt_plugin::cc_ublox::message::CfgFxn,
        cc_tools_qt_plugin::cc_ublox::message::CfgFxnPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgRxm,
        cc_tools_qt_plugin::cc_ublox::message::CfgRxmPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgEkf,
        cc_tools_qt_plugin::cc_ublox::message::CfgEkfPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgAnt,
        cc_tools_qt_plugin::cc_ublox::message::CfgAntPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgSbas,
        cc_tools_qt_plugin::cc_ublox::message::CfgSbasPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgNmeaV1,
        cc_tools_qt_plugin::cc_ublox::message::CfgNmeaV0,
        cc_tools_qt_plugin::cc_ublox::message::CfgNmea,
        cc_tools_qt_plugin::cc_ublox::message::CfgNmeaPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgUsb,
        cc_tools_qt_plugin::cc_ublox::message::CfgUsbPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgTmode,
        cc_tools_qt_plugin::cc_ublox::message::CfgTmodePoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgOdo,
        cc_tools_qt_plugin::cc_ublox::message::CfgOdoPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgNvs,
        cc_tools_qt_plugin::cc_ublox::message::CfgNavx5V3,
        cc_tools_qt_plugin::cc_ublox::message::CfgNavx5V2,
        cc_tools_qt_plugin::cc_ublox::message::CfgNavx5,
        cc_tools_qt_plugin::cc_ublox::message::CfgNavx5Poll,
        cc_tools_qt_plugin::cc_ublox::message::CfgNav5,
        cc_tools_qt_plugin::cc_ublox::message::CfgNav5Poll,
        cc_tools_qt_plugin::cc_ublox::message::CfgTp5,
        cc_tools_qt_plugin::cc_ublox::message::CfgTp5PollSelect,
        cc_tools_qt_plugin::cc_ublox::message::CfgTp5Poll,
        cc_tools_qt_plugin::cc_ublox::message::CfgPm,
        cc_tools_qt_plugin::cc_ublox::message::CfgPmPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgRinv,
        cc_tools_qt_plugin::cc_ublox::message::CfgRinvPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgItfm,
        cc_tools_qt_plugin::cc_ublox::message::CfgItfmPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgPm2V2,
        cc_tools_qt_plugin::cc_ublox::message::CfgPm2,
        cc_tools_qt_plugin::cc_ublox::message::CfgPm2Poll,
        cc_tools_qt_plugin::cc_ublox::message::CfgTmode2,
        cc_tools_qt_plugin::cc_ublox::message::CfgTmode2Poll,
        cc_tools_qt_plugin::cc_ublox::message::CfgGnss,
        cc_tools_qt_plugin::cc_ublox::message::CfgGnssPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgLogfilter,
        cc_tools_qt_plugin::cc_ublox::message::CfgLogfilterPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgTxslot,
        cc_tools_qt_plugin::cc_ublox::message::CfgPwr,
        cc_tools_qt_plugin::cc_ublox::message::CfgHnr,
        cc_tools_qt_plugin::cc_ublox::message::CfgHnrPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgEsrc,
        cc_tools_qt_plugin::cc_ublox::message::CfgEsrcPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgDosc,
        cc_tools_qt_plugin::cc_ublox::message::CfgDoscPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgSmgr,
        cc_tools_qt_plugin::cc_ublox::message::CfgSmgrPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgGeofence,
        cc_tools_qt_plugin::cc_ublox::message::CfgGeofencePoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgDgnss,
        cc_tools_qt_plugin::cc_ublox::message::CfgDgnssPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgTmode3,
        cc_tools_qt_plugin::cc_ublox::message::CfgTmode3Poll,
        cc_tools_qt_plugin::cc_ublox::message::CfgFixseed,
        cc_tools_qt_plugin::cc_ublox::message::CfgPms,
        cc_tools_qt_plugin::cc_ublox::message::CfgPmsPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgValset,
        cc_tools_qt_plugin::cc_ublox::message::CfgValget,
        cc_tools_qt_plugin::cc_ublox::message::CfgValgetPoll,
        cc_tools_qt_plugin::cc_ublox::message::CfgValdel,
        cc_tools_qt_plugin::cc_ublox::message::UpdSosRestored,
        cc_tools_qt_plugin::cc_ublox::message::UpdSosAck,
        cc_tools_qt_plugin::cc_ublox::message::UpdSosClear,
        cc_tools_qt_plugin::cc_ublox::message::UpdSosCreate,
        cc_tools_qt_plugin::cc_ublox::message::UpdSosPoll,
        cc_tools_qt_plugin::cc_ublox::message::MonIo,
        cc_tools_qt_plugin::cc_ublox::message::MonIoPoll,
        cc_tools_qt_plugin::cc_ublox::message::MonVer,
        cc_tools_qt_plugin::cc_ublox::message::MonVerPoll,
        cc_tools_qt_plugin::cc_ublox::message::MonMsgpp,
        cc_tools_qt_plugin::cc_ublox::message::MonMsgppPoll,
        cc_tools_qt_plugin::cc_ublox::message::MonRxbuf,
        cc_tools_qt_plugin::cc_ublox::message::MonRxbufPoll,
        cc_tools_qt_plugin::cc_ublox::message::MonTxbuf,
        cc_tools_qt_plugin::cc_ublox::message::MonTxbufPoll,
        cc_tools_qt_plugin::cc_ublox::message::MonHw,
        cc_tools_qt_plugin::cc_ublox::message::MonHwPoll,
        cc_tools_qt_plugin::cc_ublox::message::MonHw2,
        cc_tools_qt_plugin::cc_ublox::message::MonHw2Poll,
        cc_tools_qt_plugin::cc_ublox::message::MonRxr,
        cc_tools_qt_plugin::cc_ublox::message::MonPatch,
        cc_tools_qt_plugin::cc_ublox::message::MonPatchPoll,
        cc_tools_qt_plugin::cc_ublox::message::MonGnss,
        cc_tools_qt_plugin::cc_ublox::message::MonGnssPoll,
        cc_tools_qt_plugin::cc_ublox::message::MonSmgr,
        cc_tools_qt_plugin::cc_ublox::message::MonSmgrPoll,
        cc_tools_qt_plugin::cc_ublox::message::MonSpan,
        cc_tools_qt_plugin::cc_ublox::message::MonSpanPoll,
        cc_tools_qt_plugin::cc_ublox::message::MonComms,
        cc_tools_qt_plugin::cc_ublox::message::MonCommsPoll,
        cc_tools_qt_plugin::cc_ublox::message::MonHw3,
        cc_tools_qt_plugin::cc_ublox::message::MonHw3Poll,
        cc_tools_qt_plugin::cc_ublox::message::MonRf,
        cc_tools_qt_plugin::cc_ublox::message::MonRfPoll,
        cc_tools_qt_plugin::cc_ublox::message::AidReq,
        cc_tools_qt_plugin::cc_ublox::message::AidIni,
        cc_tools_qt_plugin::cc_ublox::message::AidIniPoll,
        cc_tools_qt_plugin::cc_ublox::message::AidHui,
        cc_tools_qt_plugin::cc_ublox::message::AidHuiPoll,
        cc_tools_qt_plugin::cc_ublox::message::AidData,
        cc_tools_qt_plugin::cc_ublox::message::AidAlm,
        cc_tools_qt_plugin::cc_ublox::message::AidAlmPollSv,
        cc_tools_qt_plugin::cc_ublox::message::AidAlmPoll,
        cc_tools_qt_plugin::cc_ublox::message::AidEph,
        cc_tools_qt_plugin::cc_ublox::message::AidEphPollSv,
        cc_tools_qt_plugin::cc_ublox::message::AidEphPoll,
        cc_tools_qt_plugin::cc_ublox::message::AidAlpsrv,
        cc_tools_qt_plugin::cc_ublox::message::AidAlpsrvToServer,
        cc_tools_qt_plugin::cc_ublox::message::AidAopU8,
        cc_tools_qt_plugin::cc_ublox::message::AidAop,
        cc_tools_qt_plugin::cc_ublox::message::AidAopPollSv,
        cc_tools_qt_plugin::cc_ublox::message::AidAopPoll,
        cc_tools_qt_plugin::cc_ublox::message::AidAlp,
        cc_tools_qt_plugin::cc_ublox::message::AidAlpStatus,
        cc_tools_qt_plugin::cc_ublox::message::AidAlpData,
        cc_tools_qt_plugin::cc_ublox::message::TimTp,
        cc_tools_qt_plugin::cc_ublox::message::TimTpPoll,
        cc_tools_qt_plugin::cc_ublox::message::TimTm2,
        cc_tools_qt_plugin::cc_ublox::message::TimTm2Poll,
        cc_tools_qt_plugin::cc_ublox::message::TimVrfy,
        cc_tools_qt_plugin::cc_ublox::message::TimVrfyPoll,
        cc_tools_qt_plugin::cc_ublox::message::TimSvin,
        cc_tools_qt_plugin::cc_ublox::message::TimSvinPoll,
        cc_tools_qt_plugin::cc_ublox::message::TimDosc,
        cc_tools_qt_plugin::cc_ublox::message::TimTos,
        cc_tools_qt_plugin::cc_ublox::message::TimSmeas,
        cc_tools_qt_plugin::cc_ublox::message::TimVcocal,
        cc_tools_qt_plugin::cc_ublox::message::TimVcocalExt,
        cc_tools_qt_plugin::cc_ublox::message::TimVcocalStop,
        cc_tools_qt_plugin::cc_ublox::message::TimVcocalPoll,
        cc_tools_qt_plugin::cc_ublox::message::TimFchg,
        cc_tools_qt_plugin::cc_ublox::message::TimFchgPoll,
        cc_tools_qt_plugin::cc_ublox::message::EsfMeas,
        cc_tools_qt_plugin::cc_ublox::message::EsfMeasPoll,
        cc_tools_qt_plugin::cc_ublox::message::EsfRaw,
        cc_tools_qt_plugin::cc_ublox::message::EsfStatus,
        cc_tools_qt_plugin::cc_ublox::message::EsfStatusPoll,
        cc_tools_qt_plugin::cc_ublox::message::EsfIns,
        cc_tools_qt_plugin::cc_ublox::message::EsfInsPoll,
        cc_tools_qt_plugin::cc_ublox::message::MgaGpsEph,
        cc_tools_qt_plugin::cc_ublox::message::MgaGpsAlm,
        cc_tools_qt_plugin::cc_ublox::message::MgaGpsHealth,
        cc_tools_qt_plugin::cc_ublox::message::MgaGpsUtc,
        cc_tools_qt_plugin::cc_ublox::message::MgaGpsIono,
        cc_tools_qt_plugin::cc_ublox::message::MgaGalEph,
        cc_tools_qt_plugin::cc_ublox::message::MgaGalAlm,
        cc_tools_qt_plugin::cc_ublox::message::MgaGalTimeoffset,
        cc_tools_qt_plugin::cc_ublox::message::MgaGalUtc,
        cc_tools_qt_plugin::cc_ublox::message::MgaBdsEph,
        cc_tools_qt_plugin::cc_ublox::message::MgaBdsAlm,
        cc_tools_qt_plugin::cc_ublox::message::MgaBdsHealth,
        cc_tools_qt_plugin::cc_ublox::message::MgaBdsUtc,
        cc_tools_qt_plugin::cc_ublox::message::MgaBdsIono,
        cc_tools_qt_plugin::cc_ublox::message::MgaQzssEph,
        cc_tools_qt_plugin::cc_ublox::message::MgaQzssAlm,
        cc_tools_qt_plugin::cc_ublox::message::MgaQzssHealth,
        cc_tools_qt_plugin::cc_ublox::message::MgaGloEph,
        cc_tools_qt_plugin::cc_ublox::message::MgaGloAlm,
        cc_tools_qt_plugin::cc_ublox::message::MgaGloTimeoffset,
        cc_tools_qt_plugin::cc_ublox::message::MgaAno,
        cc_tools_qt_plugin::cc_ublox::message::MgaFlashEph,
        cc_tools_qt_plugin::cc_ublox::message::MgaFlashAck,
        cc_tools_qt_plugin::cc_ublox::message::MgaFlashStop,
        cc_tools_qt_plugin::cc_ublox::message::MgaIniPosXyz,
        cc_tools_qt_plugin::cc_ublox::message::MgaIniPosLlh,
        cc_tools_qt_plugin::cc_ublox::message::MgaIniTimeUtc,
        cc_tools_qt_plugin::cc_ublox::message::MgaIniTimeGnss,
        cc_tools_qt_plugin::cc_ublox::message::MgaIniClkd,
        cc_tools_qt_plugin::cc_ublox::message::MgaIniFreq,
        cc_tools_qt_plugin::cc_ublox::message::MgaIniEop,
        cc_tools_qt_plugin::cc_ublox::message::MgaAck,
        cc_tools_qt_plugin::cc_ublox::message::MgaDbd,
        cc_tools_qt_plugin::cc_ublox::message::MgaDbdPoll,
        cc_tools_qt_plugin::cc_ublox::message::LogErase,
        cc_tools_qt_plugin::cc_ublox::message::LogString,
        cc_tools_qt_plugin::cc_ublox::message::LogCreate,
        cc_tools_qt_plugin::cc_ublox::message::LogInfo,
        cc_tools_qt_plugin::cc_ublox::message::LogInfoPoll,
        cc_tools_qt_plugin::cc_ublox::message::LogRetrieve,
        cc_tools_qt_plugin::cc_ublox::message::LogRetrievepos,
        cc_tools_qt_plugin::cc_ublox::message::LogRetrievestring,
        cc_tools_qt_plugin::cc_ublox::message::LogFindtime,
        cc_tools_qt_plugin::cc_ublox::message::LogFindtimeResp,
        cc_tools_qt_plugin::cc_ublox::message::LogRetrieveposextra,
        cc_tools_qt_plugin::cc_ublox::message::LogRetrievebatch,
        cc_tools_qt_plugin::cc_ublox::message::LogBatch,
        cc_tools_qt_plugin::cc_ublox::message::SecSign,
        cc_tools_qt_plugin::cc_ublox::message::SecUniqid,
        cc_tools_qt_plugin::cc_ublox::message::SecUniqidPoll,
        cc_tools_qt_plugin::cc_ublox::message::HnrPvt,
        cc_tools_qt_plugin::cc_ublox::message::HnrPvtPoll
    >;

} // namespace input

} // namespace cc_ublox

} // namespace cc_tools_qt_plugin
