// Generated by commsdsl2tools_qt v7.0.2

#include "Plugin_CC_UBLOX.h"

#include "Protocol_CC_UBLOX.h"

namespace cc_tools_qt_plugin
{

namespace cc_ublox
{

namespace plugin
{

Plugin_CC_UBLOX::Plugin_CC_UBLOX() :
    Base(Type_Protocol)
{
}

Plugin_CC_UBLOX::~Plugin_CC_UBLOX() = default;

cc_tools_qt::ToolsProtocolPtr Plugin_CC_UBLOX::createProtocolImpl()
{
    return cc_tools_qt::ToolsProtocolPtr(new Protocol_CC_UBLOX());
}

} // namespace plugin

} // namespace cc_ublox

} // namespace cc_tools_qt_plugin
