// Generated by commsdsl2tools_qt v7.1.0

#include "AidAlpsrvToServer.h"

#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/Message.h"
#include "cc_ublox/message/AidAlpsrvToServer.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_ublox
{

namespace message
{

class AidAlpsrvToServerImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_ublox::Message,
        ::cc_ublox::message::AidAlpsrvToServer,
        AidAlpsrvToServerImpl
    >
{
public:
    AidAlpsrvToServerImpl() = default;
    AidAlpsrvToServerImpl(const AidAlpsrvToServerImpl&) = default;
    AidAlpsrvToServerImpl(AidAlpsrvToServerImpl&&) = default;
    virtual ~AidAlpsrvToServerImpl() = default;
    AidAlpsrvToServerImpl& operator=(const AidAlpsrvToServerImpl&) = default;
    AidAlpsrvToServerImpl& operator=(AidAlpsrvToServerImpl&&) = default;
};

AidAlpsrvToServer::AidAlpsrvToServer() : m_pImpl(new AidAlpsrvToServerImpl) {}
AidAlpsrvToServer::~AidAlpsrvToServer() = default;

AidAlpsrvToServer& AidAlpsrvToServer::operator=(const AidAlpsrvToServer& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

AidAlpsrvToServer& AidAlpsrvToServer::operator=(AidAlpsrvToServer&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* AidAlpsrvToServer::nameImpl() const
{
    return m_pImpl->name();
}

bool AidAlpsrvToServer::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong AidAlpsrvToServer::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString AidAlpsrvToServer::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void AidAlpsrvToServer::resetImpl()
{
    m_pImpl->reset();
}

bool AidAlpsrvToServer::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const AidAlpsrvToServer*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool AidAlpsrvToServer::isValidImpl() const
{
    return m_pImpl->isValid();
}

AidAlpsrvToServer::DataSeq AidAlpsrvToServer::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool AidAlpsrvToServer::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

AidAlpsrvToServer::Ptr AidAlpsrvToServer::cloneImpl() const
{
    ImplPtr impl(static_cast<AidAlpsrvToServerImpl*>(m_pImpl->clone().release()));
    return Ptr(new AidAlpsrvToServer(std::move(impl)));
}

void AidAlpsrvToServer::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

AidAlpsrvToServer::DataSeq AidAlpsrvToServer::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

AidAlpsrvToServer::FieldsList AidAlpsrvToServer::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

AidAlpsrvToServer::FieldsList AidAlpsrvToServer::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

AidAlpsrvToServer::AidAlpsrvToServer(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_ublox

} // namespace Message

} // namespace cc_tools_qt_plugin
