// Generated by commsdsl2tools_qt v7.1.0

#include "AidAlpsrv.h"

#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/Message.h"
#include "cc_ublox/message/AidAlpsrv.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_ublox
{

namespace message
{

class AidAlpsrvImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_ublox::Message,
        ::cc_ublox::message::AidAlpsrv,
        AidAlpsrvImpl
    >
{
public:
    AidAlpsrvImpl() = default;
    AidAlpsrvImpl(const AidAlpsrvImpl&) = default;
    AidAlpsrvImpl(AidAlpsrvImpl&&) = default;
    virtual ~AidAlpsrvImpl() = default;
    AidAlpsrvImpl& operator=(const AidAlpsrvImpl&) = default;
    AidAlpsrvImpl& operator=(AidAlpsrvImpl&&) = default;
};

AidAlpsrv::AidAlpsrv() : m_pImpl(new AidAlpsrvImpl) {}
AidAlpsrv::~AidAlpsrv() = default;

AidAlpsrv& AidAlpsrv::operator=(const AidAlpsrv& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

AidAlpsrv& AidAlpsrv::operator=(AidAlpsrv&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* AidAlpsrv::nameImpl() const
{
    return m_pImpl->name();
}

bool AidAlpsrv::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong AidAlpsrv::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString AidAlpsrv::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void AidAlpsrv::resetImpl()
{
    m_pImpl->reset();
}

bool AidAlpsrv::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const AidAlpsrv*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool AidAlpsrv::isValidImpl() const
{
    return m_pImpl->isValid();
}

AidAlpsrv::DataSeq AidAlpsrv::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool AidAlpsrv::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

AidAlpsrv::Ptr AidAlpsrv::cloneImpl() const
{
    ImplPtr impl(static_cast<AidAlpsrvImpl*>(m_pImpl->clone().release()));
    return Ptr(new AidAlpsrv(std::move(impl)));
}

void AidAlpsrv::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

AidAlpsrv::DataSeq AidAlpsrv::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

AidAlpsrv::FieldsList AidAlpsrv::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

AidAlpsrv::FieldsList AidAlpsrv::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

AidAlpsrv::AidAlpsrv(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_ublox

} // namespace Message

} // namespace cc_tools_qt_plugin
