// Generated by commsdsl2tools_qt v7.0.0

#include "CfgEsrcPoll.h"

#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/Message.h"
#include "cc_ublox/message/CfgEsrcPoll.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_ublox
{

namespace message
{

class CfgEsrcPollImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_ublox::Message,
        ::cc_ublox::message::CfgEsrcPoll,
        CfgEsrcPollImpl
    >
{
public:
    CfgEsrcPollImpl() = default;
    CfgEsrcPollImpl(const CfgEsrcPollImpl&) = default;
    CfgEsrcPollImpl(CfgEsrcPollImpl&&) = default;
    virtual ~CfgEsrcPollImpl() = default;
    CfgEsrcPollImpl& operator=(const CfgEsrcPollImpl&) = default;
    CfgEsrcPollImpl& operator=(CfgEsrcPollImpl&&) = default;
};

CfgEsrcPoll::CfgEsrcPoll() : m_pImpl(new CfgEsrcPollImpl) {}
CfgEsrcPoll::~CfgEsrcPoll() = default;

CfgEsrcPoll& CfgEsrcPoll::operator=(const CfgEsrcPoll& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

CfgEsrcPoll& CfgEsrcPoll::operator=(CfgEsrcPoll&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* CfgEsrcPoll::nameImpl() const
{
    return m_pImpl->name();
}

bool CfgEsrcPoll::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong CfgEsrcPoll::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString CfgEsrcPoll::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void CfgEsrcPoll::resetImpl()
{
    m_pImpl->reset();
}

bool CfgEsrcPoll::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const CfgEsrcPoll*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool CfgEsrcPoll::isValidImpl() const
{
    return m_pImpl->isValid();
}

CfgEsrcPoll::DataSeq CfgEsrcPoll::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool CfgEsrcPoll::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

CfgEsrcPoll::Ptr CfgEsrcPoll::cloneImpl() const
{
    ImplPtr impl(static_cast<CfgEsrcPollImpl*>(m_pImpl->clone().release()));
    return Ptr(new CfgEsrcPoll(std::move(impl)));
}

void CfgEsrcPoll::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

CfgEsrcPoll::DataSeq CfgEsrcPoll::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

CfgEsrcPoll::FieldsList CfgEsrcPoll::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

CfgEsrcPoll::FieldsList CfgEsrcPoll::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

CfgEsrcPoll::CfgEsrcPoll(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_ublox

} // namespace Message

} // namespace cc_tools_qt_plugin
