// Generated by commsdsl2tools_qt v7.1.0

#include "CfgEkf.h"

#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/Message.h"
#include "cc_ublox/message/CfgEkf.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_ublox
{

namespace message
{

class CfgEkfImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_ublox::Message,
        ::cc_ublox::message::CfgEkf,
        CfgEkfImpl
    >
{
public:
    CfgEkfImpl() = default;
    CfgEkfImpl(const CfgEkfImpl&) = default;
    CfgEkfImpl(CfgEkfImpl&&) = default;
    virtual ~CfgEkfImpl() = default;
    CfgEkfImpl& operator=(const CfgEkfImpl&) = default;
    CfgEkfImpl& operator=(CfgEkfImpl&&) = default;
};

CfgEkf::CfgEkf() : m_pImpl(new CfgEkfImpl) {}
CfgEkf::~CfgEkf() = default;

CfgEkf& CfgEkf::operator=(const CfgEkf& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

CfgEkf& CfgEkf::operator=(CfgEkf&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* CfgEkf::nameImpl() const
{
    return m_pImpl->name();
}

bool CfgEkf::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong CfgEkf::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString CfgEkf::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void CfgEkf::resetImpl()
{
    m_pImpl->reset();
}

bool CfgEkf::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const CfgEkf*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool CfgEkf::isValidImpl() const
{
    return m_pImpl->isValid();
}

CfgEkf::DataSeq CfgEkf::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool CfgEkf::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

CfgEkf::Ptr CfgEkf::cloneImpl() const
{
    ImplPtr impl(static_cast<CfgEkfImpl*>(m_pImpl->clone().release()));
    return Ptr(new CfgEkf(std::move(impl)));
}

void CfgEkf::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

CfgEkf::DataSeq CfgEkf::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

CfgEkf::FieldsList CfgEkf::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

CfgEkf::FieldsList CfgEkf::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

CfgEkf::CfgEkf(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_ublox

} // namespace Message

} // namespace cc_tools_qt_plugin
