// Generated by commsdsl2tools_qt v7.3.0

#include "CfgGeofence.h"

#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/Message.h"
#include "cc_ublox/message/CfgGeofence.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_ublox
{

namespace message
{

class CfgGeofenceImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_ublox::Message,
        ::cc_ublox::message::CfgGeofence,
        CfgGeofenceImpl
    >
{
public:
    CfgGeofenceImpl() = default;
    CfgGeofenceImpl(const CfgGeofenceImpl&) = default;
    CfgGeofenceImpl(CfgGeofenceImpl&&) = default;
    virtual ~CfgGeofenceImpl() = default;
    CfgGeofenceImpl& operator=(const CfgGeofenceImpl&) = default;
    CfgGeofenceImpl& operator=(CfgGeofenceImpl&&) = default;
};

CfgGeofence::CfgGeofence() : m_pImpl(new CfgGeofenceImpl) {}
CfgGeofence::~CfgGeofence() = default;

CfgGeofence& CfgGeofence::operator=(const CfgGeofence& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

CfgGeofence& CfgGeofence::operator=(CfgGeofence&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* CfgGeofence::nameImpl() const
{
    return m_pImpl->name();
}

bool CfgGeofence::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong CfgGeofence::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString CfgGeofence::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void CfgGeofence::resetImpl()
{
    m_pImpl->reset();
}

bool CfgGeofence::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const CfgGeofence*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool CfgGeofence::isValidImpl() const
{
    return m_pImpl->isValid();
}

CfgGeofence::DataSeq CfgGeofence::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool CfgGeofence::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

CfgGeofence::Ptr CfgGeofence::cloneImpl() const
{
    ImplPtr impl(static_cast<CfgGeofenceImpl*>(m_pImpl->clone().release()));
    return Ptr(new CfgGeofence(std::move(impl)));
}

void CfgGeofence::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

CfgGeofence::DataSeq CfgGeofence::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

CfgGeofence::FieldsList CfgGeofence::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

CfgGeofence::FieldsList CfgGeofence::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

CfgGeofence::CfgGeofence(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_ublox

} // namespace Message

} // namespace cc_tools_qt_plugin
