// Generated by commsdsl2tools_qt v8.0.0

#include "CfgGnssPoll.h"

#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/Message.h"
#include "cc_ublox/message/CfgGnssPoll.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_ublox
{

namespace message
{

class CfgGnssPollImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_ublox::Message,
        ::cc_ublox::message::CfgGnssPoll,
        CfgGnssPollImpl
    >
{
public:
    CfgGnssPollImpl() = default;
    CfgGnssPollImpl(const CfgGnssPollImpl&) = default;
    CfgGnssPollImpl(CfgGnssPollImpl&&) = default;
    virtual ~CfgGnssPollImpl() = default;
    CfgGnssPollImpl& operator=(const CfgGnssPollImpl&) = default;
    CfgGnssPollImpl& operator=(CfgGnssPollImpl&&) = default;
};

CfgGnssPoll::CfgGnssPoll() : m_pImpl(new CfgGnssPollImpl) {}
CfgGnssPoll::~CfgGnssPoll() = default;

CfgGnssPoll& CfgGnssPoll::operator=(const CfgGnssPoll& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

CfgGnssPoll& CfgGnssPoll::operator=(CfgGnssPoll&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* CfgGnssPoll::nameImpl() const
{
    return m_pImpl->name();
}

bool CfgGnssPoll::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong CfgGnssPoll::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString CfgGnssPoll::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void CfgGnssPoll::resetImpl()
{
    m_pImpl->reset();
}

bool CfgGnssPoll::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const CfgGnssPoll*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool CfgGnssPoll::isValidImpl() const
{
    return m_pImpl->isValid();
}

CfgGnssPoll::DataSeq CfgGnssPoll::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool CfgGnssPoll::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

CfgGnssPoll::Ptr CfgGnssPoll::cloneImpl() const
{
    ImplPtr impl(static_cast<CfgGnssPollImpl*>(m_pImpl->clone().release()));
    return Ptr(new CfgGnssPoll(std::move(impl)));
}

void CfgGnssPoll::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

CfgGnssPoll::DataSeq CfgGnssPoll::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

CfgGnssPoll::FieldsList CfgGnssPoll::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

CfgGnssPoll::FieldsList CfgGnssPoll::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

CfgGnssPoll::CfgGnssPoll(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_ublox

} // namespace Message

} // namespace cc_tools_qt_plugin
