// Generated by commsdsl2tools_qt v7.0.3

#include "CfgHnr.h"

#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/Message.h"
#include "cc_ublox/message/CfgHnr.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_ublox
{

namespace message
{

class CfgHnrImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_ublox::Message,
        ::cc_ublox::message::CfgHnr,
        CfgHnrImpl
    >
{
public:
    CfgHnrImpl() = default;
    CfgHnrImpl(const CfgHnrImpl&) = default;
    CfgHnrImpl(CfgHnrImpl&&) = default;
    virtual ~CfgHnrImpl() = default;
    CfgHnrImpl& operator=(const CfgHnrImpl&) = default;
    CfgHnrImpl& operator=(CfgHnrImpl&&) = default;
};

CfgHnr::CfgHnr() : m_pImpl(new CfgHnrImpl) {}
CfgHnr::~CfgHnr() = default;

CfgHnr& CfgHnr::operator=(const CfgHnr& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

CfgHnr& CfgHnr::operator=(CfgHnr&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* CfgHnr::nameImpl() const
{
    return m_pImpl->name();
}

bool CfgHnr::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong CfgHnr::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString CfgHnr::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void CfgHnr::resetImpl()
{
    m_pImpl->reset();
}

bool CfgHnr::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const CfgHnr*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool CfgHnr::isValidImpl() const
{
    return m_pImpl->isValid();
}

CfgHnr::DataSeq CfgHnr::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool CfgHnr::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

CfgHnr::Ptr CfgHnr::cloneImpl() const
{
    ImplPtr impl(static_cast<CfgHnrImpl*>(m_pImpl->clone().release()));
    return Ptr(new CfgHnr(std::move(impl)));
}

void CfgHnr::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

CfgHnr::DataSeq CfgHnr::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

CfgHnr::FieldsList CfgHnr::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

CfgHnr::FieldsList CfgHnr::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

CfgHnr::CfgHnr(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_ublox

} // namespace Message

} // namespace cc_tools_qt_plugin
