// Generated by commsdsl2tools_qt v7.3.0

#include "CfgLogfilterPoll.h"

#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/Message.h"
#include "cc_ublox/message/CfgLogfilterPoll.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_ublox
{

namespace message
{

class CfgLogfilterPollImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_ublox::Message,
        ::cc_ublox::message::CfgLogfilterPoll,
        CfgLogfilterPollImpl
    >
{
public:
    CfgLogfilterPollImpl() = default;
    CfgLogfilterPollImpl(const CfgLogfilterPollImpl&) = default;
    CfgLogfilterPollImpl(CfgLogfilterPollImpl&&) = default;
    virtual ~CfgLogfilterPollImpl() = default;
    CfgLogfilterPollImpl& operator=(const CfgLogfilterPollImpl&) = default;
    CfgLogfilterPollImpl& operator=(CfgLogfilterPollImpl&&) = default;
};

CfgLogfilterPoll::CfgLogfilterPoll() : m_pImpl(new CfgLogfilterPollImpl) {}
CfgLogfilterPoll::~CfgLogfilterPoll() = default;

CfgLogfilterPoll& CfgLogfilterPoll::operator=(const CfgLogfilterPoll& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

CfgLogfilterPoll& CfgLogfilterPoll::operator=(CfgLogfilterPoll&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* CfgLogfilterPoll::nameImpl() const
{
    return m_pImpl->name();
}

bool CfgLogfilterPoll::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong CfgLogfilterPoll::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString CfgLogfilterPoll::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void CfgLogfilterPoll::resetImpl()
{
    m_pImpl->reset();
}

bool CfgLogfilterPoll::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const CfgLogfilterPoll*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool CfgLogfilterPoll::isValidImpl() const
{
    return m_pImpl->isValid();
}

CfgLogfilterPoll::DataSeq CfgLogfilterPoll::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool CfgLogfilterPoll::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

CfgLogfilterPoll::Ptr CfgLogfilterPoll::cloneImpl() const
{
    ImplPtr impl(static_cast<CfgLogfilterPollImpl*>(m_pImpl->clone().release()));
    return Ptr(new CfgLogfilterPoll(std::move(impl)));
}

void CfgLogfilterPoll::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

CfgLogfilterPoll::DataSeq CfgLogfilterPoll::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

CfgLogfilterPoll::FieldsList CfgLogfilterPoll::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

CfgLogfilterPoll::FieldsList CfgLogfilterPoll::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

CfgLogfilterPoll::CfgLogfilterPoll(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_ublox

} // namespace Message

} // namespace cc_tools_qt_plugin
