// Generated by commsdsl2tools_qt v7.1.0

#include "CfgNavx5V3.h"

#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/Message.h"
#include "cc_ublox/message/CfgNavx5V3.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_ublox
{

namespace message
{

class CfgNavx5V3Impl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_ublox::Message,
        ::cc_ublox::message::CfgNavx5V3,
        CfgNavx5V3Impl
    >
{
public:
    CfgNavx5V3Impl() = default;
    CfgNavx5V3Impl(const CfgNavx5V3Impl&) = default;
    CfgNavx5V3Impl(CfgNavx5V3Impl&&) = default;
    virtual ~CfgNavx5V3Impl() = default;
    CfgNavx5V3Impl& operator=(const CfgNavx5V3Impl&) = default;
    CfgNavx5V3Impl& operator=(CfgNavx5V3Impl&&) = default;
};

CfgNavx5V3::CfgNavx5V3() : m_pImpl(new CfgNavx5V3Impl) {}
CfgNavx5V3::~CfgNavx5V3() = default;

CfgNavx5V3& CfgNavx5V3::operator=(const CfgNavx5V3& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

CfgNavx5V3& CfgNavx5V3::operator=(CfgNavx5V3&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* CfgNavx5V3::nameImpl() const
{
    return m_pImpl->name();
}

bool CfgNavx5V3::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong CfgNavx5V3::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString CfgNavx5V3::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void CfgNavx5V3::resetImpl()
{
    m_pImpl->reset();
}

bool CfgNavx5V3::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const CfgNavx5V3*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool CfgNavx5V3::isValidImpl() const
{
    return m_pImpl->isValid();
}

CfgNavx5V3::DataSeq CfgNavx5V3::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool CfgNavx5V3::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

CfgNavx5V3::Ptr CfgNavx5V3::cloneImpl() const
{
    ImplPtr impl(static_cast<CfgNavx5V3Impl*>(m_pImpl->clone().release()));
    return Ptr(new CfgNavx5V3(std::move(impl)));
}

void CfgNavx5V3::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

CfgNavx5V3::DataSeq CfgNavx5V3::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

CfgNavx5V3::FieldsList CfgNavx5V3::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

CfgNavx5V3::FieldsList CfgNavx5V3::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

CfgNavx5V3::CfgNavx5V3(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_ublox

} // namespace Message

} // namespace cc_tools_qt_plugin
