// Generated by commsdsl2tools_qt v7.0.0

#include "CfgSmgr.h"

#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/Message.h"
#include "cc_ublox/message/CfgSmgr.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_ublox
{

namespace message
{

class CfgSmgrImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_ublox::Message,
        ::cc_ublox::message::CfgSmgr,
        CfgSmgrImpl
    >
{
public:
    CfgSmgrImpl() = default;
    CfgSmgrImpl(const CfgSmgrImpl&) = default;
    CfgSmgrImpl(CfgSmgrImpl&&) = default;
    virtual ~CfgSmgrImpl() = default;
    CfgSmgrImpl& operator=(const CfgSmgrImpl&) = default;
    CfgSmgrImpl& operator=(CfgSmgrImpl&&) = default;
};

CfgSmgr::CfgSmgr() : m_pImpl(new CfgSmgrImpl) {}
CfgSmgr::~CfgSmgr() = default;

CfgSmgr& CfgSmgr::operator=(const CfgSmgr& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

CfgSmgr& CfgSmgr::operator=(CfgSmgr&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* CfgSmgr::nameImpl() const
{
    return m_pImpl->name();
}

bool CfgSmgr::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong CfgSmgr::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString CfgSmgr::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void CfgSmgr::resetImpl()
{
    m_pImpl->reset();
}

bool CfgSmgr::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const CfgSmgr*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool CfgSmgr::isValidImpl() const
{
    return m_pImpl->isValid();
}

CfgSmgr::DataSeq CfgSmgr::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool CfgSmgr::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

CfgSmgr::Ptr CfgSmgr::cloneImpl() const
{
    ImplPtr impl(static_cast<CfgSmgrImpl*>(m_pImpl->clone().release()));
    return Ptr(new CfgSmgr(std::move(impl)));
}

void CfgSmgr::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

CfgSmgr::DataSeq CfgSmgr::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

CfgSmgr::FieldsList CfgSmgr::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

CfgSmgr::FieldsList CfgSmgr::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

CfgSmgr::CfgSmgr(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_ublox

} // namespace Message

} // namespace cc_tools_qt_plugin
