// Generated by commsdsl2tools_qt v7.0.3

#include "EsfStatusPoll.h"

#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/Message.h"
#include "cc_ublox/message/EsfStatusPoll.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_ublox
{

namespace message
{

class EsfStatusPollImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_ublox::Message,
        ::cc_ublox::message::EsfStatusPoll,
        EsfStatusPollImpl
    >
{
public:
    EsfStatusPollImpl() = default;
    EsfStatusPollImpl(const EsfStatusPollImpl&) = default;
    EsfStatusPollImpl(EsfStatusPollImpl&&) = default;
    virtual ~EsfStatusPollImpl() = default;
    EsfStatusPollImpl& operator=(const EsfStatusPollImpl&) = default;
    EsfStatusPollImpl& operator=(EsfStatusPollImpl&&) = default;
};

EsfStatusPoll::EsfStatusPoll() : m_pImpl(new EsfStatusPollImpl) {}
EsfStatusPoll::~EsfStatusPoll() = default;

EsfStatusPoll& EsfStatusPoll::operator=(const EsfStatusPoll& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

EsfStatusPoll& EsfStatusPoll::operator=(EsfStatusPoll&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* EsfStatusPoll::nameImpl() const
{
    return m_pImpl->name();
}

bool EsfStatusPoll::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong EsfStatusPoll::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString EsfStatusPoll::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void EsfStatusPoll::resetImpl()
{
    m_pImpl->reset();
}

bool EsfStatusPoll::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const EsfStatusPoll*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool EsfStatusPoll::isValidImpl() const
{
    return m_pImpl->isValid();
}

EsfStatusPoll::DataSeq EsfStatusPoll::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool EsfStatusPoll::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

EsfStatusPoll::Ptr EsfStatusPoll::cloneImpl() const
{
    ImplPtr impl(static_cast<EsfStatusPollImpl*>(m_pImpl->clone().release()));
    return Ptr(new EsfStatusPoll(std::move(impl)));
}

void EsfStatusPoll::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

EsfStatusPoll::DataSeq EsfStatusPoll::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

EsfStatusPoll::FieldsList EsfStatusPoll::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

EsfStatusPoll::FieldsList EsfStatusPoll::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

EsfStatusPoll::EsfStatusPoll(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_ublox

} // namespace Message

} // namespace cc_tools_qt_plugin
