// Generated by commsdsl2tools_qt v7.1.0

#include "InfWarning.h"

#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/Message.h"
#include "cc_ublox/message/InfWarning.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_ublox
{

namespace message
{

class InfWarningImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_ublox::Message,
        ::cc_ublox::message::InfWarning,
        InfWarningImpl
    >
{
public:
    InfWarningImpl() = default;
    InfWarningImpl(const InfWarningImpl&) = default;
    InfWarningImpl(InfWarningImpl&&) = default;
    virtual ~InfWarningImpl() = default;
    InfWarningImpl& operator=(const InfWarningImpl&) = default;
    InfWarningImpl& operator=(InfWarningImpl&&) = default;
};

InfWarning::InfWarning() : m_pImpl(new InfWarningImpl) {}
InfWarning::~InfWarning() = default;

InfWarning& InfWarning::operator=(const InfWarning& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

InfWarning& InfWarning::operator=(InfWarning&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* InfWarning::nameImpl() const
{
    return m_pImpl->name();
}

bool InfWarning::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong InfWarning::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString InfWarning::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void InfWarning::resetImpl()
{
    m_pImpl->reset();
}

bool InfWarning::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const InfWarning*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool InfWarning::isValidImpl() const
{
    return m_pImpl->isValid();
}

InfWarning::DataSeq InfWarning::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool InfWarning::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

InfWarning::Ptr InfWarning::cloneImpl() const
{
    ImplPtr impl(static_cast<InfWarningImpl*>(m_pImpl->clone().release()));
    return Ptr(new InfWarning(std::move(impl)));
}

void InfWarning::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

InfWarning::DataSeq InfWarning::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

InfWarning::FieldsList InfWarning::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

InfWarning::FieldsList InfWarning::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

InfWarning::InfWarning(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_ublox

} // namespace Message

} // namespace cc_tools_qt_plugin
