// Generated by commsdsl2tools_qt v8.0.0

#include "MgaGpsHealth.h"

#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/Message.h"
#include "cc_ublox/message/MgaGpsHealth.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_ublox
{

namespace message
{

class MgaGpsHealthImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_ublox::Message,
        ::cc_ublox::message::MgaGpsHealth,
        MgaGpsHealthImpl
    >
{
public:
    MgaGpsHealthImpl() = default;
    MgaGpsHealthImpl(const MgaGpsHealthImpl&) = default;
    MgaGpsHealthImpl(MgaGpsHealthImpl&&) = default;
    virtual ~MgaGpsHealthImpl() = default;
    MgaGpsHealthImpl& operator=(const MgaGpsHealthImpl&) = default;
    MgaGpsHealthImpl& operator=(MgaGpsHealthImpl&&) = default;
};

MgaGpsHealth::MgaGpsHealth() : m_pImpl(new MgaGpsHealthImpl) {}
MgaGpsHealth::~MgaGpsHealth() = default;

MgaGpsHealth& MgaGpsHealth::operator=(const MgaGpsHealth& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

MgaGpsHealth& MgaGpsHealth::operator=(MgaGpsHealth&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* MgaGpsHealth::nameImpl() const
{
    return m_pImpl->name();
}

bool MgaGpsHealth::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong MgaGpsHealth::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString MgaGpsHealth::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void MgaGpsHealth::resetImpl()
{
    m_pImpl->reset();
}

bool MgaGpsHealth::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const MgaGpsHealth*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool MgaGpsHealth::isValidImpl() const
{
    return m_pImpl->isValid();
}

MgaGpsHealth::DataSeq MgaGpsHealth::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool MgaGpsHealth::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

MgaGpsHealth::Ptr MgaGpsHealth::cloneImpl() const
{
    ImplPtr impl(static_cast<MgaGpsHealthImpl*>(m_pImpl->clone().release()));
    return Ptr(new MgaGpsHealth(std::move(impl)));
}

void MgaGpsHealth::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

MgaGpsHealth::DataSeq MgaGpsHealth::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

MgaGpsHealth::FieldsList MgaGpsHealth::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

MgaGpsHealth::FieldsList MgaGpsHealth::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

MgaGpsHealth::MgaGpsHealth(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_ublox

} // namespace Message

} // namespace cc_tools_qt_plugin
