// Generated by commsdsl2tools_qt v7.0.2

#include "MgaGloEph.h"

#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/Message.h"
#include "cc_ublox/message/MgaGloEph.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_ublox
{

namespace message
{

class MgaGloEphImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_ublox::Message,
        ::cc_ublox::message::MgaGloEph,
        MgaGloEphImpl
    >
{
public:
    MgaGloEphImpl() = default;
    MgaGloEphImpl(const MgaGloEphImpl&) = default;
    MgaGloEphImpl(MgaGloEphImpl&&) = default;
    virtual ~MgaGloEphImpl() = default;
    MgaGloEphImpl& operator=(const MgaGloEphImpl&) = default;
    MgaGloEphImpl& operator=(MgaGloEphImpl&&) = default;
};

MgaGloEph::MgaGloEph() : m_pImpl(new MgaGloEphImpl) {}
MgaGloEph::~MgaGloEph() = default;

MgaGloEph& MgaGloEph::operator=(const MgaGloEph& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

MgaGloEph& MgaGloEph::operator=(MgaGloEph&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* MgaGloEph::nameImpl() const
{
    return m_pImpl->name();
}

bool MgaGloEph::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong MgaGloEph::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString MgaGloEph::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void MgaGloEph::resetImpl()
{
    m_pImpl->reset();
}

bool MgaGloEph::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const MgaGloEph*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool MgaGloEph::isValidImpl() const
{
    return m_pImpl->isValid();
}

MgaGloEph::DataSeq MgaGloEph::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool MgaGloEph::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

MgaGloEph::Ptr MgaGloEph::cloneImpl() const
{
    ImplPtr impl(static_cast<MgaGloEphImpl*>(m_pImpl->clone().release()));
    return Ptr(new MgaGloEph(std::move(impl)));
}

void MgaGloEph::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

MgaGloEph::DataSeq MgaGloEph::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

MgaGloEph::FieldsList MgaGloEph::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

MgaGloEph::FieldsList MgaGloEph::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

MgaGloEph::MgaGloEph(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_ublox

} // namespace Message

} // namespace cc_tools_qt_plugin
