// Generated by commsdsl2tools_qt v7.3.0

#include "MgaIniPosXyz.h"

#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/Message.h"
#include "cc_ublox/message/MgaIniPosXyz.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_ublox
{

namespace message
{

class MgaIniPosXyzImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_ublox::Message,
        ::cc_ublox::message::MgaIniPosXyz,
        MgaIniPosXyzImpl
    >
{
public:
    MgaIniPosXyzImpl() = default;
    MgaIniPosXyzImpl(const MgaIniPosXyzImpl&) = default;
    MgaIniPosXyzImpl(MgaIniPosXyzImpl&&) = default;
    virtual ~MgaIniPosXyzImpl() = default;
    MgaIniPosXyzImpl& operator=(const MgaIniPosXyzImpl&) = default;
    MgaIniPosXyzImpl& operator=(MgaIniPosXyzImpl&&) = default;
};

MgaIniPosXyz::MgaIniPosXyz() : m_pImpl(new MgaIniPosXyzImpl) {}
MgaIniPosXyz::~MgaIniPosXyz() = default;

MgaIniPosXyz& MgaIniPosXyz::operator=(const MgaIniPosXyz& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

MgaIniPosXyz& MgaIniPosXyz::operator=(MgaIniPosXyz&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* MgaIniPosXyz::nameImpl() const
{
    return m_pImpl->name();
}

bool MgaIniPosXyz::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong MgaIniPosXyz::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString MgaIniPosXyz::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void MgaIniPosXyz::resetImpl()
{
    m_pImpl->reset();
}

bool MgaIniPosXyz::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const MgaIniPosXyz*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool MgaIniPosXyz::isValidImpl() const
{
    return m_pImpl->isValid();
}

MgaIniPosXyz::DataSeq MgaIniPosXyz::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool MgaIniPosXyz::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

MgaIniPosXyz::Ptr MgaIniPosXyz::cloneImpl() const
{
    ImplPtr impl(static_cast<MgaIniPosXyzImpl*>(m_pImpl->clone().release()));
    return Ptr(new MgaIniPosXyz(std::move(impl)));
}

void MgaIniPosXyz::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

MgaIniPosXyz::DataSeq MgaIniPosXyz::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

MgaIniPosXyz::FieldsList MgaIniPosXyz::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

MgaIniPosXyz::FieldsList MgaIniPosXyz::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

MgaIniPosXyz::MgaIniPosXyz(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_ublox

} // namespace Message

} // namespace cc_tools_qt_plugin
