// Generated by commsdsl2tools_qt v7.0.3

#include "MonMsgpp.h"

#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/Message.h"
#include "cc_ublox/message/MonMsgpp.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_ublox
{

namespace message
{

class MonMsgppImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_ublox::Message,
        ::cc_ublox::message::MonMsgpp,
        MonMsgppImpl
    >
{
public:
    MonMsgppImpl() = default;
    MonMsgppImpl(const MonMsgppImpl&) = default;
    MonMsgppImpl(MonMsgppImpl&&) = default;
    virtual ~MonMsgppImpl() = default;
    MonMsgppImpl& operator=(const MonMsgppImpl&) = default;
    MonMsgppImpl& operator=(MonMsgppImpl&&) = default;
};

MonMsgpp::MonMsgpp() : m_pImpl(new MonMsgppImpl) {}
MonMsgpp::~MonMsgpp() = default;

MonMsgpp& MonMsgpp::operator=(const MonMsgpp& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

MonMsgpp& MonMsgpp::operator=(MonMsgpp&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* MonMsgpp::nameImpl() const
{
    return m_pImpl->name();
}

bool MonMsgpp::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong MonMsgpp::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString MonMsgpp::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void MonMsgpp::resetImpl()
{
    m_pImpl->reset();
}

bool MonMsgpp::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const MonMsgpp*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool MonMsgpp::isValidImpl() const
{
    return m_pImpl->isValid();
}

MonMsgpp::DataSeq MonMsgpp::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool MonMsgpp::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

MonMsgpp::Ptr MonMsgpp::cloneImpl() const
{
    ImplPtr impl(static_cast<MonMsgppImpl*>(m_pImpl->clone().release()));
    return Ptr(new MonMsgpp(std::move(impl)));
}

void MonMsgpp::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

MonMsgpp::DataSeq MonMsgpp::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

MonMsgpp::FieldsList MonMsgpp::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

MonMsgpp::FieldsList MonMsgpp::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

MonMsgpp::MonMsgpp(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_ublox

} // namespace Message

} // namespace cc_tools_qt_plugin
