// Generated by commsdsl2tools_qt v8.0.0

#include "MonRxbufPoll.h"

#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/Message.h"
#include "cc_ublox/message/MonRxbufPoll.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_ublox
{

namespace message
{

class MonRxbufPollImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_ublox::Message,
        ::cc_ublox::message::MonRxbufPoll,
        MonRxbufPollImpl
    >
{
public:
    MonRxbufPollImpl() = default;
    MonRxbufPollImpl(const MonRxbufPollImpl&) = default;
    MonRxbufPollImpl(MonRxbufPollImpl&&) = default;
    virtual ~MonRxbufPollImpl() = default;
    MonRxbufPollImpl& operator=(const MonRxbufPollImpl&) = default;
    MonRxbufPollImpl& operator=(MonRxbufPollImpl&&) = default;
};

MonRxbufPoll::MonRxbufPoll() : m_pImpl(new MonRxbufPollImpl) {}
MonRxbufPoll::~MonRxbufPoll() = default;

MonRxbufPoll& MonRxbufPoll::operator=(const MonRxbufPoll& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

MonRxbufPoll& MonRxbufPoll::operator=(MonRxbufPoll&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* MonRxbufPoll::nameImpl() const
{
    return m_pImpl->name();
}

bool MonRxbufPoll::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong MonRxbufPoll::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString MonRxbufPoll::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void MonRxbufPoll::resetImpl()
{
    m_pImpl->reset();
}

bool MonRxbufPoll::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const MonRxbufPoll*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool MonRxbufPoll::isValidImpl() const
{
    return m_pImpl->isValid();
}

MonRxbufPoll::DataSeq MonRxbufPoll::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool MonRxbufPoll::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

MonRxbufPoll::Ptr MonRxbufPoll::cloneImpl() const
{
    ImplPtr impl(static_cast<MonRxbufPollImpl*>(m_pImpl->clone().release()));
    return Ptr(new MonRxbufPoll(std::move(impl)));
}

void MonRxbufPoll::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

MonRxbufPoll::DataSeq MonRxbufPoll::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

MonRxbufPoll::FieldsList MonRxbufPoll::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

MonRxbufPoll::FieldsList MonRxbufPoll::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

MonRxbufPoll::MonRxbufPoll(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_ublox

} // namespace Message

} // namespace cc_tools_qt_plugin
