// Generated by commsdsl2tools_qt v7.3.0

#include "NavDgps.h"

#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/Message.h"
#include "cc_ublox/message/NavDgps.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_ublox
{

namespace message
{

class NavDgpsImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_ublox::Message,
        ::cc_ublox::message::NavDgps,
        NavDgpsImpl
    >
{
public:
    NavDgpsImpl() = default;
    NavDgpsImpl(const NavDgpsImpl&) = default;
    NavDgpsImpl(NavDgpsImpl&&) = default;
    virtual ~NavDgpsImpl() = default;
    NavDgpsImpl& operator=(const NavDgpsImpl&) = default;
    NavDgpsImpl& operator=(NavDgpsImpl&&) = default;
};

NavDgps::NavDgps() : m_pImpl(new NavDgpsImpl) {}
NavDgps::~NavDgps() = default;

NavDgps& NavDgps::operator=(const NavDgps& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

NavDgps& NavDgps::operator=(NavDgps&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* NavDgps::nameImpl() const
{
    return m_pImpl->name();
}

bool NavDgps::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong NavDgps::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString NavDgps::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void NavDgps::resetImpl()
{
    m_pImpl->reset();
}

bool NavDgps::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const NavDgps*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool NavDgps::isValidImpl() const
{
    return m_pImpl->isValid();
}

NavDgps::DataSeq NavDgps::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool NavDgps::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

NavDgps::Ptr NavDgps::cloneImpl() const
{
    ImplPtr impl(static_cast<NavDgpsImpl*>(m_pImpl->clone().release()));
    return Ptr(new NavDgps(std::move(impl)));
}

void NavDgps::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

NavDgps::DataSeq NavDgps::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

NavDgps::FieldsList NavDgps::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

NavDgps::FieldsList NavDgps::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

NavDgps::NavDgps(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_ublox

} // namespace Message

} // namespace cc_tools_qt_plugin
