// Generated by commsdsl2tools_qt v7.0.0

#include "NavSigPoll.h"

#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/Message.h"
#include "cc_ublox/message/NavSigPoll.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_ublox
{

namespace message
{

class NavSigPollImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_ublox::Message,
        ::cc_ublox::message::NavSigPoll,
        NavSigPollImpl
    >
{
public:
    NavSigPollImpl() = default;
    NavSigPollImpl(const NavSigPollImpl&) = default;
    NavSigPollImpl(NavSigPollImpl&&) = default;
    virtual ~NavSigPollImpl() = default;
    NavSigPollImpl& operator=(const NavSigPollImpl&) = default;
    NavSigPollImpl& operator=(NavSigPollImpl&&) = default;
};

NavSigPoll::NavSigPoll() : m_pImpl(new NavSigPollImpl) {}
NavSigPoll::~NavSigPoll() = default;

NavSigPoll& NavSigPoll::operator=(const NavSigPoll& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

NavSigPoll& NavSigPoll::operator=(NavSigPoll&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* NavSigPoll::nameImpl() const
{
    return m_pImpl->name();
}

bool NavSigPoll::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong NavSigPoll::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString NavSigPoll::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void NavSigPoll::resetImpl()
{
    m_pImpl->reset();
}

bool NavSigPoll::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const NavSigPoll*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool NavSigPoll::isValidImpl() const
{
    return m_pImpl->isValid();
}

NavSigPoll::DataSeq NavSigPoll::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool NavSigPoll::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

NavSigPoll::Ptr NavSigPoll::cloneImpl() const
{
    ImplPtr impl(static_cast<NavSigPollImpl*>(m_pImpl->clone().release()));
    return Ptr(new NavSigPoll(std::move(impl)));
}

void NavSigPoll::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

NavSigPoll::DataSeq NavSigPoll::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

NavSigPoll::FieldsList NavSigPoll::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

NavSigPoll::FieldsList NavSigPoll::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

NavSigPoll::NavSigPoll(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_ublox

} // namespace Message

} // namespace cc_tools_qt_plugin
