// Generated by commsdsl2tools_qt v7.0.3

#include "NavTimegpsPoll.h"

#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/Message.h"
#include "cc_ublox/message/NavTimegpsPoll.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_ublox
{

namespace message
{

class NavTimegpsPollImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_ublox::Message,
        ::cc_ublox::message::NavTimegpsPoll,
        NavTimegpsPollImpl
    >
{
public:
    NavTimegpsPollImpl() = default;
    NavTimegpsPollImpl(const NavTimegpsPollImpl&) = default;
    NavTimegpsPollImpl(NavTimegpsPollImpl&&) = default;
    virtual ~NavTimegpsPollImpl() = default;
    NavTimegpsPollImpl& operator=(const NavTimegpsPollImpl&) = default;
    NavTimegpsPollImpl& operator=(NavTimegpsPollImpl&&) = default;
};

NavTimegpsPoll::NavTimegpsPoll() : m_pImpl(new NavTimegpsPollImpl) {}
NavTimegpsPoll::~NavTimegpsPoll() = default;

NavTimegpsPoll& NavTimegpsPoll::operator=(const NavTimegpsPoll& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

NavTimegpsPoll& NavTimegpsPoll::operator=(NavTimegpsPoll&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* NavTimegpsPoll::nameImpl() const
{
    return m_pImpl->name();
}

bool NavTimegpsPoll::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong NavTimegpsPoll::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString NavTimegpsPoll::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void NavTimegpsPoll::resetImpl()
{
    m_pImpl->reset();
}

bool NavTimegpsPoll::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const NavTimegpsPoll*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool NavTimegpsPoll::isValidImpl() const
{
    return m_pImpl->isValid();
}

NavTimegpsPoll::DataSeq NavTimegpsPoll::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool NavTimegpsPoll::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

NavTimegpsPoll::Ptr NavTimegpsPoll::cloneImpl() const
{
    ImplPtr impl(static_cast<NavTimegpsPollImpl*>(m_pImpl->clone().release()));
    return Ptr(new NavTimegpsPoll(std::move(impl)));
}

void NavTimegpsPoll::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

NavTimegpsPoll::DataSeq NavTimegpsPoll::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

NavTimegpsPoll::FieldsList NavTimegpsPoll::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

NavTimegpsPoll::FieldsList NavTimegpsPoll::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

NavTimegpsPoll::NavTimegpsPoll(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_ublox

} // namespace Message

} // namespace cc_tools_qt_plugin
