// Generated by commsdsl2tools_qt v7.1.0

#include "RxmEph.h"

#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/Message.h"
#include "cc_ublox/message/RxmEph.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_ublox
{

namespace message
{

class RxmEphImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_ublox::Message,
        ::cc_ublox::message::RxmEph,
        RxmEphImpl
    >
{
public:
    RxmEphImpl() = default;
    RxmEphImpl(const RxmEphImpl&) = default;
    RxmEphImpl(RxmEphImpl&&) = default;
    virtual ~RxmEphImpl() = default;
    RxmEphImpl& operator=(const RxmEphImpl&) = default;
    RxmEphImpl& operator=(RxmEphImpl&&) = default;
};

RxmEph::RxmEph() : m_pImpl(new RxmEphImpl) {}
RxmEph::~RxmEph() = default;

RxmEph& RxmEph::operator=(const RxmEph& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

RxmEph& RxmEph::operator=(RxmEph&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* RxmEph::nameImpl() const
{
    return m_pImpl->name();
}

bool RxmEph::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong RxmEph::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString RxmEph::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void RxmEph::resetImpl()
{
    m_pImpl->reset();
}

bool RxmEph::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const RxmEph*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool RxmEph::isValidImpl() const
{
    return m_pImpl->isValid();
}

RxmEph::DataSeq RxmEph::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool RxmEph::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

RxmEph::Ptr RxmEph::cloneImpl() const
{
    ImplPtr impl(static_cast<RxmEphImpl*>(m_pImpl->clone().release()));
    return Ptr(new RxmEph(std::move(impl)));
}

void RxmEph::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

RxmEph::DataSeq RxmEph::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

RxmEph::FieldsList RxmEph::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

RxmEph::FieldsList RxmEph::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

RxmEph::RxmEph(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_ublox

} // namespace Message

} // namespace cc_tools_qt_plugin
