// Generated by commsdsl2tools_qt v7.1.0

#include "RxmSfrb.h"

#include "cc_tools_qt/ToolsMessageBase.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/Message.h"
#include "cc_ublox/message/RxmSfrb.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_ublox
{

namespace message
{

class RxmSfrbImpl : public
    cc_tools_qt::ToolsMessageBase<
        cc_tools_qt_plugin::Message::cc_ublox::Message,
        ::cc_ublox::message::RxmSfrb,
        RxmSfrbImpl
    >
{
public:
    RxmSfrbImpl() = default;
    RxmSfrbImpl(const RxmSfrbImpl&) = default;
    RxmSfrbImpl(RxmSfrbImpl&&) = default;
    virtual ~RxmSfrbImpl() = default;
    RxmSfrbImpl& operator=(const RxmSfrbImpl&) = default;
    RxmSfrbImpl& operator=(RxmSfrbImpl&&) = default;
};

RxmSfrb::RxmSfrb() : m_pImpl(new RxmSfrbImpl) {}
RxmSfrb::~RxmSfrb() = default;

RxmSfrb& RxmSfrb::operator=(const RxmSfrb& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

RxmSfrb& RxmSfrb::operator=(RxmSfrb&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

const char* RxmSfrb::nameImpl() const
{
    return m_pImpl->name();
}

bool RxmSfrb::refreshMsgImpl()
{
    return m_pImpl->refreshMsg();
}

qlonglong RxmSfrb::numericIdImpl() const
{
    return m_pImpl->numericId();
}

QString RxmSfrb::idAsStringImpl() const
{
    return m_pImpl->idAsString();
}

void RxmSfrb::resetImpl()
{
    m_pImpl->reset();
}

bool RxmSfrb::assignImpl(const cc_tools_qt::ToolsMessage& other)
{
    auto* castedOther = dynamic_cast<const RxmSfrb*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

bool RxmSfrb::isValidImpl() const
{
    return m_pImpl->isValid();
}

RxmSfrb::DataSeq RxmSfrb::encodeDataImpl() const
{
    return m_pImpl->encodeData();
}

bool RxmSfrb::decodeDataImpl(const DataSeq& data)
{
    return m_pImpl->decodeData(data);
}

RxmSfrb::Ptr RxmSfrb::cloneImpl() const
{
    ImplPtr impl(static_cast<RxmSfrbImpl*>(m_pImpl->clone().release()));
    return Ptr(new RxmSfrb(std::move(impl)));
}

void RxmSfrb::assignProtMessageImpl(void* protMsg)
{
    m_pImpl->assignProtMessage(protMsg);
}

RxmSfrb::DataSeq RxmSfrb::encodeFramedImpl(cc_tools_qt::ToolsFrame& frame) const
{
    return m_pImpl->encodeFramed(frame);
}

RxmSfrb::FieldsList RxmSfrb::transportFieldsImpl()
{
    return m_pImpl->transportFields();
}

RxmSfrb::FieldsList RxmSfrb::payloadFieldsImpl()
{
    return m_pImpl->payloadFields();
}

RxmSfrb::RxmSfrb(ImplPtr&& impl) :
    m_pImpl(std::move(impl))
{
}

} // namespace message

} // namespace cc_ublox

} // namespace Message

} // namespace cc_tools_qt_plugin
