// Generated by commsdsl2tools_qt v6.3.3

#include "AckAck.h"

#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_ublox/field/MsgId.h"
#include "cc_tools_qt_plugin/cc_ublox/options/DefaultOptions.h"
#include "cc_ublox/message/AckAck.h"

namespace cc_tools_qt_plugin
{

namespace cc_ublox
{

namespace message
{

namespace
{

static QVariantMap createProps_msgId(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::AckAckFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::MsgId;
    auto props = cc_tools_qt_plugin::cc_ublox::field::createProps_msgId(Field::name(), serHidden);
    return props;
}

QVariantList createProps()
{
    QVariantList props;
    props.append(createProps_msgId(false));
    return props;
}

} // namespace

class AckAckImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_ublox::message::AckAck<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>,
        AckAckImpl
    >
{
public:
    AckAckImpl() = default;
    AckAckImpl(const AckAckImpl&) = delete;
    AckAckImpl(AckAckImpl&&) = delete;
    virtual ~AckAckImpl() = default;
    AckAckImpl& operator=(const AckAckImpl&) = default;
    AckAckImpl& operator=(AckAckImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

AckAck::AckAck() : m_pImpl(new AckAckImpl) {}
AckAck::~AckAck() = default;

AckAck& AckAck::operator=(const AckAck& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

AckAck& AckAck::operator=(AckAck&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

AckAck::MsgIdParamType AckAck::doGetId()
{
    return ::cc_ublox::message::AckAck<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::doGetId();
}

const char* AckAck::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& AckAck::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void AckAck::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void AckAck::resetImpl()
{
    m_pImpl->reset();
}

bool AckAck::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const AckAck*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

AckAck::MsgIdParamType AckAck::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus AckAck::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus AckAck::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool AckAck::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t AckAck::lengthImpl() const
{
    return m_pImpl->length();
}

bool AckAck::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_ublox

} // namespace cc_tools_qt_plugin
