// Generated by commsdsl2tools_qt v6.3.2

#include "AidAopPollSv.h"

#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_ublox/options/DefaultOptions.h"
#include "cc_ublox/message/AidAopPollSv.h"

namespace cc_tools_qt_plugin
{

namespace cc_ublox
{

namespace message
{

namespace
{

static QVariantMap createProps_svid(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::AidAopPollSvFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Svid;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .asMap();
}

QVariantList createProps()
{
    QVariantList props;
    props.append(createProps_svid(false));
    return props;
}

} // namespace

class AidAopPollSvImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_ublox::message::AidAopPollSv<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>,
        AidAopPollSvImpl
    >
{
public:
    AidAopPollSvImpl() = default;
    AidAopPollSvImpl(const AidAopPollSvImpl&) = delete;
    AidAopPollSvImpl(AidAopPollSvImpl&&) = delete;
    virtual ~AidAopPollSvImpl() = default;
    AidAopPollSvImpl& operator=(const AidAopPollSvImpl&) = default;
    AidAopPollSvImpl& operator=(AidAopPollSvImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

AidAopPollSv::AidAopPollSv() : m_pImpl(new AidAopPollSvImpl) {}
AidAopPollSv::~AidAopPollSv() = default;

AidAopPollSv& AidAopPollSv::operator=(const AidAopPollSv& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

AidAopPollSv& AidAopPollSv::operator=(AidAopPollSv&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

AidAopPollSv::MsgIdParamType AidAopPollSv::doGetId()
{
    return ::cc_ublox::message::AidAopPollSv<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::doGetId();
}

const char* AidAopPollSv::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& AidAopPollSv::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void AidAopPollSv::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void AidAopPollSv::resetImpl()
{
    m_pImpl->reset();
}

bool AidAopPollSv::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const AidAopPollSv*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

AidAopPollSv::MsgIdParamType AidAopPollSv::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus AidAopPollSv::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus AidAopPollSv::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool AidAopPollSv::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t AidAopPollSv::lengthImpl() const
{
    return m_pImpl->length();
}

bool AidAopPollSv::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_ublox

} // namespace cc_tools_qt_plugin
