// Generated by commsdsl2tools_qt v6.3.4

#include "AidData.h"

#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_ublox/options/DefaultOptions.h"
#include "cc_ublox/message/AidData.h"

namespace cc_tools_qt_plugin
{

namespace cc_ublox
{

namespace message
{

namespace
{

QVariantList createProps()
{
    QVariantList props;
    return props;
}

} // namespace

class AidDataImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_ublox::message::AidData<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>,
        AidDataImpl
    >
{
public:
    AidDataImpl() = default;
    AidDataImpl(const AidDataImpl&) = delete;
    AidDataImpl(AidDataImpl&&) = delete;
    virtual ~AidDataImpl() = default;
    AidDataImpl& operator=(const AidDataImpl&) = default;
    AidDataImpl& operator=(AidDataImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

AidData::AidData() : m_pImpl(new AidDataImpl) {}
AidData::~AidData() = default;

AidData& AidData::operator=(const AidData& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

AidData& AidData::operator=(AidData&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

AidData::MsgIdParamType AidData::doGetId()
{
    return ::cc_ublox::message::AidData<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::doGetId();
}

const char* AidData::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& AidData::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void AidData::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void AidData::resetImpl()
{
    m_pImpl->reset();
}

bool AidData::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const AidData*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

AidData::MsgIdParamType AidData::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus AidData::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus AidData::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool AidData::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t AidData::lengthImpl() const
{
    return m_pImpl->length();
}

bool AidData::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_ublox

} // namespace cc_tools_qt_plugin
