// Generated by commsdsl2tools_qt v6.3.3

#include "AidHuiPoll.h"

#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_ublox/options/DefaultOptions.h"
#include "cc_ublox/message/AidHuiPoll.h"

namespace cc_tools_qt_plugin
{

namespace cc_ublox
{

namespace message
{

namespace
{

QVariantList createProps()
{
    QVariantList props;
    return props;
}

} // namespace

class AidHuiPollImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_ublox::message::AidHuiPoll<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>,
        AidHuiPollImpl
    >
{
public:
    AidHuiPollImpl() = default;
    AidHuiPollImpl(const AidHuiPollImpl&) = delete;
    AidHuiPollImpl(AidHuiPollImpl&&) = delete;
    virtual ~AidHuiPollImpl() = default;
    AidHuiPollImpl& operator=(const AidHuiPollImpl&) = default;
    AidHuiPollImpl& operator=(AidHuiPollImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

AidHuiPoll::AidHuiPoll() : m_pImpl(new AidHuiPollImpl) {}
AidHuiPoll::~AidHuiPoll() = default;

AidHuiPoll& AidHuiPoll::operator=(const AidHuiPoll& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

AidHuiPoll& AidHuiPoll::operator=(AidHuiPoll&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

AidHuiPoll::MsgIdParamType AidHuiPoll::doGetId()
{
    return ::cc_ublox::message::AidHuiPoll<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::doGetId();
}

const char* AidHuiPoll::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& AidHuiPoll::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void AidHuiPoll::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void AidHuiPoll::resetImpl()
{
    m_pImpl->reset();
}

bool AidHuiPoll::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const AidHuiPoll*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

AidHuiPoll::MsgIdParamType AidHuiPoll::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus AidHuiPoll::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus AidHuiPoll::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool AidHuiPoll::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t AidHuiPoll::lengthImpl() const
{
    return m_pImpl->length();
}

bool AidHuiPoll::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_ublox

} // namespace cc_tools_qt_plugin
