// Generated by commsdsl2tools_qt v6.3.2

#include "CfgRinv.h"

#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_ublox/options/DefaultOptions.h"
#include "cc_ublox/message/CfgRinv.h"

namespace cc_tools_qt_plugin
{

namespace cc_ublox
{

namespace message
{

namespace
{

static QVariantMap createProps_flags(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::CfgRinvFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Flags;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .add(0U, "dump")
            .add(1U, "binary")
            .asMap();
}

static QVariantMap createProps_data(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::CfgRinvFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Data;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .asMap();
}

QVariantList createProps()
{
    QVariantList props;
    props.append(createProps_flags(false));
    props.append(createProps_data(false));
    return props;
}

} // namespace

class CfgRinvImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_ublox::message::CfgRinv<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>,
        CfgRinvImpl
    >
{
public:
    CfgRinvImpl() = default;
    CfgRinvImpl(const CfgRinvImpl&) = delete;
    CfgRinvImpl(CfgRinvImpl&&) = delete;
    virtual ~CfgRinvImpl() = default;
    CfgRinvImpl& operator=(const CfgRinvImpl&) = default;
    CfgRinvImpl& operator=(CfgRinvImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

CfgRinv::CfgRinv() : m_pImpl(new CfgRinvImpl) {}
CfgRinv::~CfgRinv() = default;

CfgRinv& CfgRinv::operator=(const CfgRinv& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

CfgRinv& CfgRinv::operator=(CfgRinv&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

CfgRinv::MsgIdParamType CfgRinv::doGetId()
{
    return ::cc_ublox::message::CfgRinv<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::doGetId();
}

const char* CfgRinv::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& CfgRinv::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void CfgRinv::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void CfgRinv::resetImpl()
{
    m_pImpl->reset();
}

bool CfgRinv::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const CfgRinv*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

CfgRinv::MsgIdParamType CfgRinv::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus CfgRinv::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus CfgRinv::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool CfgRinv::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t CfgRinv::lengthImpl() const
{
    return m_pImpl->length();
}

bool CfgRinv::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_ublox

} // namespace cc_tools_qt_plugin
