// Generated by commsdsl2tools_qt v6.3.2

#include "CfgTpPoll.h"

#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_ublox/options/DefaultOptions.h"
#include "cc_ublox/message/CfgTpPoll.h"

namespace cc_tools_qt_plugin
{

namespace cc_ublox
{

namespace message
{

namespace
{

QVariantList createProps()
{
    QVariantList props;
    return props;
}

} // namespace

class CfgTpPollImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_ublox::message::CfgTpPoll<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>,
        CfgTpPollImpl
    >
{
public:
    CfgTpPollImpl() = default;
    CfgTpPollImpl(const CfgTpPollImpl&) = delete;
    CfgTpPollImpl(CfgTpPollImpl&&) = delete;
    virtual ~CfgTpPollImpl() = default;
    CfgTpPollImpl& operator=(const CfgTpPollImpl&) = default;
    CfgTpPollImpl& operator=(CfgTpPollImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

CfgTpPoll::CfgTpPoll() : m_pImpl(new CfgTpPollImpl) {}
CfgTpPoll::~CfgTpPoll() = default;

CfgTpPoll& CfgTpPoll::operator=(const CfgTpPoll& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

CfgTpPoll& CfgTpPoll::operator=(CfgTpPoll&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

CfgTpPoll::MsgIdParamType CfgTpPoll::doGetId()
{
    return ::cc_ublox::message::CfgTpPoll<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::doGetId();
}

const char* CfgTpPoll::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& CfgTpPoll::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void CfgTpPoll::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void CfgTpPoll::resetImpl()
{
    m_pImpl->reset();
}

bool CfgTpPoll::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const CfgTpPoll*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

CfgTpPoll::MsgIdParamType CfgTpPoll::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus CfgTpPoll::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus CfgTpPoll::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool CfgTpPoll::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t CfgTpPoll::lengthImpl() const
{
    return m_pImpl->length();
}

bool CfgTpPoll::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_ublox

} // namespace cc_tools_qt_plugin
