// Generated by commsdsl2tools_qt v6.3.4

#include "CfgValget.h"

#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_ublox/field/CfgValLayer.h"
#include "cc_tools_qt_plugin/cc_ublox/field/CfgValPairSimple.h"
#include "cc_tools_qt_plugin/cc_ublox/options/DefaultOptions.h"
#include "cc_ublox/message/CfgValget.h"

namespace cc_tools_qt_plugin
{

namespace cc_ublox
{

namespace message
{

namespace
{

static QVariantMap createProps_version(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::CfgValgetFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Version;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .readOnly()
            .asMap();
}

static QVariantMap createProps_layer(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::CfgValgetFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Layer;
    auto props = cc_tools_qt_plugin::cc_ublox::field::createProps_cfgValLayer(Field::name(), serHidden);
    return props;
}

static QVariantMap createProps_position(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::CfgValgetFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Position;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .asMap();
}

struct CfgdataMembers
{
    static QVariantMap createProps_element(bool serHidden)
    {
        static_cast<void>(serHidden);
        using Field = ::cc_ublox::message::CfgValgetFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::CfgdataMembers::Element;
        auto props = cc_tools_qt_plugin::cc_ublox::field::createProps_cfgValPairSimple(Field::name(), serHidden);
        return props;
    }
}; // struct CfgdataMembers

static QVariantMap createProps_cfgdata(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::CfgValgetFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Cfgdata;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .serialisedHidden()
            .add(CfgdataMembers::createProps_element(serHidden))
            .appendIndexToElementName()
            .asMap();
}

QVariantList createProps()
{
    QVariantList props;
    props.append(createProps_version(false));
    props.append(createProps_layer(false));
    props.append(createProps_position(false));
    props.append(createProps_cfgdata(false));
    return props;
}

} // namespace

class CfgValgetImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_ublox::message::CfgValget<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>,
        CfgValgetImpl
    >
{
public:
    CfgValgetImpl() = default;
    CfgValgetImpl(const CfgValgetImpl&) = delete;
    CfgValgetImpl(CfgValgetImpl&&) = delete;
    virtual ~CfgValgetImpl() = default;
    CfgValgetImpl& operator=(const CfgValgetImpl&) = default;
    CfgValgetImpl& operator=(CfgValgetImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

CfgValget::CfgValget() : m_pImpl(new CfgValgetImpl) {}
CfgValget::~CfgValget() = default;

CfgValget& CfgValget::operator=(const CfgValget& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

CfgValget& CfgValget::operator=(CfgValget&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

CfgValget::MsgIdParamType CfgValget::doGetId()
{
    return ::cc_ublox::message::CfgValget<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::doGetId();
}

const char* CfgValget::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& CfgValget::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void CfgValget::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void CfgValget::resetImpl()
{
    m_pImpl->reset();
}

bool CfgValget::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const CfgValget*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

CfgValget::MsgIdParamType CfgValget::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus CfgValget::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus CfgValget::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool CfgValget::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t CfgValget::lengthImpl() const
{
    return m_pImpl->length();
}

bool CfgValget::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_ublox

} // namespace cc_tools_qt_plugin
