// Generated by commsdsl2tools_qt v6.3.2

#include "InfNotice.h"

#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_ublox/options/DefaultOptions.h"
#include "cc_ublox/message/InfNotice.h"

namespace cc_tools_qt_plugin
{

namespace cc_ublox
{

namespace message
{

namespace
{

static QVariantMap createProps_str(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::InfNoticeFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Str;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .asMap();
}

QVariantList createProps()
{
    QVariantList props;
    props.append(createProps_str(false));
    return props;
}

} // namespace

class InfNoticeImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_ublox::message::InfNotice<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>,
        InfNoticeImpl
    >
{
public:
    InfNoticeImpl() = default;
    InfNoticeImpl(const InfNoticeImpl&) = delete;
    InfNoticeImpl(InfNoticeImpl&&) = delete;
    virtual ~InfNoticeImpl() = default;
    InfNoticeImpl& operator=(const InfNoticeImpl&) = default;
    InfNoticeImpl& operator=(InfNoticeImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

InfNotice::InfNotice() : m_pImpl(new InfNoticeImpl) {}
InfNotice::~InfNotice() = default;

InfNotice& InfNotice::operator=(const InfNotice& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

InfNotice& InfNotice::operator=(InfNotice&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

InfNotice::MsgIdParamType InfNotice::doGetId()
{
    return ::cc_ublox::message::InfNotice<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::doGetId();
}

const char* InfNotice::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& InfNotice::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void InfNotice::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void InfNotice::resetImpl()
{
    m_pImpl->reset();
}

bool InfNotice::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const InfNotice*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

InfNotice::MsgIdParamType InfNotice::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus InfNotice::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus InfNotice::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool InfNotice::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t InfNotice::lengthImpl() const
{
    return m_pImpl->length();
}

bool InfNotice::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_ublox

} // namespace cc_tools_qt_plugin
