// Generated by commsdsl2tools_qt v6.3.4

#include "MgaFlashStop.h"

#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_ublox/options/DefaultOptions.h"
#include "cc_ublox/message/MgaFlashStop.h"

namespace cc_tools_qt_plugin
{

namespace cc_ublox
{

namespace message
{

namespace
{

static QVariantMap createProps_type(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::MgaFlashStopFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Type;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .readOnly()
            .asMap();
}

static QVariantMap createProps_version(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::MgaFlashStopFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Version;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .asMap();
}

QVariantList createProps()
{
    QVariantList props;
    props.append(createProps_type(false));
    props.append(createProps_version(false));
    return props;
}

} // namespace

class MgaFlashStopImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_ublox::message::MgaFlashStop<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>,
        MgaFlashStopImpl
    >
{
public:
    MgaFlashStopImpl() = default;
    MgaFlashStopImpl(const MgaFlashStopImpl&) = delete;
    MgaFlashStopImpl(MgaFlashStopImpl&&) = delete;
    virtual ~MgaFlashStopImpl() = default;
    MgaFlashStopImpl& operator=(const MgaFlashStopImpl&) = default;
    MgaFlashStopImpl& operator=(MgaFlashStopImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

MgaFlashStop::MgaFlashStop() : m_pImpl(new MgaFlashStopImpl) {}
MgaFlashStop::~MgaFlashStop() = default;

MgaFlashStop& MgaFlashStop::operator=(const MgaFlashStop& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

MgaFlashStop& MgaFlashStop::operator=(MgaFlashStop&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

MgaFlashStop::MsgIdParamType MgaFlashStop::doGetId()
{
    return ::cc_ublox::message::MgaFlashStop<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::doGetId();
}

const char* MgaFlashStop::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& MgaFlashStop::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void MgaFlashStop::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void MgaFlashStop::resetImpl()
{
    m_pImpl->reset();
}

bool MgaFlashStop::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const MgaFlashStop*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

MgaFlashStop::MsgIdParamType MgaFlashStop::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus MgaFlashStop::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus MgaFlashStop::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool MgaFlashStop::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t MgaFlashStop::lengthImpl() const
{
    return m_pImpl->length();
}

bool MgaFlashStop::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_ublox

} // namespace cc_tools_qt_plugin
