// Generated by commsdsl2tools_qt v6.3.3

#include "MgaIniPosLlh.h"

#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_ublox/field/Lat.h"
#include "cc_tools_qt_plugin/cc_ublox/field/Lon.h"
#include "cc_tools_qt_plugin/cc_ublox/field/Res2.h"
#include "cc_tools_qt_plugin/cc_ublox/options/DefaultOptions.h"
#include "cc_ublox/message/MgaIniPosLlh.h"

namespace cc_tools_qt_plugin
{

namespace cc_ublox
{

namespace message
{

namespace
{

static QVariantMap createProps_type(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::MgaIniPosLlhFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Type;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .readOnly()
            .asMap();
}

static QVariantMap createProps_version(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::MgaIniPosLlhFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Version;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .asMap();
}

static QVariantMap createProps_reserved1(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::MgaIniPosLlhFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Reserved1;
    auto props = cc_tools_qt_plugin::cc_ublox::field::createProps_res2(Field::name(), serHidden);
    return props;
}

static QVariantMap createProps_lat(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::MgaIniPosLlhFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Lat;
    auto props = cc_tools_qt_plugin::cc_ublox::field::createProps_lat(Field::name(), serHidden);
    return props;
}

static QVariantMap createProps_lon(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::MgaIniPosLlhFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Lon;
    auto props = cc_tools_qt_plugin::cc_ublox::field::createProps_lon(Field::name(), serHidden);
    return props;
}

static QVariantMap createProps_alt(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::MgaIniPosLlhFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Alt;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .asMap();
}

static QVariantMap createProps_posAcc(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::MgaIniPosLlhFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::PosAcc;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .asMap();
}

QVariantList createProps()
{
    QVariantList props;
    props.append(createProps_type(false));
    props.append(createProps_version(false));
    props.append(createProps_reserved1(false));
    props.append(createProps_lat(false));
    props.append(createProps_lon(false));
    props.append(createProps_alt(false));
    props.append(createProps_posAcc(false));
    return props;
}

} // namespace

class MgaIniPosLlhImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_ublox::message::MgaIniPosLlh<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>,
        MgaIniPosLlhImpl
    >
{
public:
    MgaIniPosLlhImpl() = default;
    MgaIniPosLlhImpl(const MgaIniPosLlhImpl&) = delete;
    MgaIniPosLlhImpl(MgaIniPosLlhImpl&&) = delete;
    virtual ~MgaIniPosLlhImpl() = default;
    MgaIniPosLlhImpl& operator=(const MgaIniPosLlhImpl&) = default;
    MgaIniPosLlhImpl& operator=(MgaIniPosLlhImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

MgaIniPosLlh::MgaIniPosLlh() : m_pImpl(new MgaIniPosLlhImpl) {}
MgaIniPosLlh::~MgaIniPosLlh() = default;

MgaIniPosLlh& MgaIniPosLlh::operator=(const MgaIniPosLlh& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

MgaIniPosLlh& MgaIniPosLlh::operator=(MgaIniPosLlh&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

MgaIniPosLlh::MsgIdParamType MgaIniPosLlh::doGetId()
{
    return ::cc_ublox::message::MgaIniPosLlh<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::doGetId();
}

const char* MgaIniPosLlh::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& MgaIniPosLlh::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void MgaIniPosLlh::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void MgaIniPosLlh::resetImpl()
{
    m_pImpl->reset();
}

bool MgaIniPosLlh::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const MgaIniPosLlh*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

MgaIniPosLlh::MsgIdParamType MgaIniPosLlh::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus MgaIniPosLlh::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus MgaIniPosLlh::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool MgaIniPosLlh::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t MgaIniPosLlh::lengthImpl() const
{
    return m_pImpl->length();
}

bool MgaIniPosLlh::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_ublox

} // namespace cc_tools_qt_plugin
