// Generated by commsdsl2tools_qt v6.3.2

#include "MonRfPoll.h"

#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_ublox/options/DefaultOptions.h"
#include "cc_ublox/message/MonRfPoll.h"

namespace cc_tools_qt_plugin
{

namespace cc_ublox
{

namespace message
{

namespace
{

QVariantList createProps()
{
    QVariantList props;
    return props;
}

} // namespace

class MonRfPollImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_ublox::message::MonRfPoll<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>,
        MonRfPollImpl
    >
{
public:
    MonRfPollImpl() = default;
    MonRfPollImpl(const MonRfPollImpl&) = delete;
    MonRfPollImpl(MonRfPollImpl&&) = delete;
    virtual ~MonRfPollImpl() = default;
    MonRfPollImpl& operator=(const MonRfPollImpl&) = default;
    MonRfPollImpl& operator=(MonRfPollImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

MonRfPoll::MonRfPoll() : m_pImpl(new MonRfPollImpl) {}
MonRfPoll::~MonRfPoll() = default;

MonRfPoll& MonRfPoll::operator=(const MonRfPoll& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

MonRfPoll& MonRfPoll::operator=(MonRfPoll&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

MonRfPoll::MsgIdParamType MonRfPoll::doGetId()
{
    return ::cc_ublox::message::MonRfPoll<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::doGetId();
}

const char* MonRfPoll::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& MonRfPoll::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void MonRfPoll::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void MonRfPoll::resetImpl()
{
    m_pImpl->reset();
}

bool MonRfPoll::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const MonRfPoll*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

MonRfPoll::MsgIdParamType MonRfPoll::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus MonRfPoll::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus MonRfPoll::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool MonRfPoll::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t MonRfPoll::lengthImpl() const
{
    return m_pImpl->length();
}

bool MonRfPoll::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_ublox

} // namespace cc_tools_qt_plugin
