// Generated by commsdsl2tools_qt v6.3.0

#include "MonSpanPoll.h"

#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_ublox/options/DefaultOptions.h"
#include "cc_ublox/message/MonSpanPoll.h"

namespace cc_tools_qt_plugin
{

namespace cc_ublox
{

namespace message
{

namespace
{

QVariantList createProps()
{
    QVariantList props;
    return props;
}

} // namespace

class MonSpanPollImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_ublox::message::MonSpanPoll<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>,
        MonSpanPollImpl
    >
{
public:
    MonSpanPollImpl() = default;
    MonSpanPollImpl(const MonSpanPollImpl&) = delete;
    MonSpanPollImpl(MonSpanPollImpl&&) = delete;
    virtual ~MonSpanPollImpl() = default;
    MonSpanPollImpl& operator=(const MonSpanPollImpl&) = default;
    MonSpanPollImpl& operator=(MonSpanPollImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

MonSpanPoll::MonSpanPoll() : m_pImpl(new MonSpanPollImpl) {}
MonSpanPoll::~MonSpanPoll() = default;

MonSpanPoll& MonSpanPoll::operator=(const MonSpanPoll& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

MonSpanPoll& MonSpanPoll::operator=(MonSpanPoll&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

MonSpanPoll::MsgIdParamType MonSpanPoll::doGetId()
{
    return ::cc_ublox::message::MonSpanPoll<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::doGetId();
}

const char* MonSpanPoll::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& MonSpanPoll::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void MonSpanPoll::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void MonSpanPoll::resetImpl()
{
    m_pImpl->reset();
}

bool MonSpanPoll::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const MonSpanPoll*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

MonSpanPoll::MsgIdParamType MonSpanPoll::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus MonSpanPoll::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus MonSpanPoll::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool MonSpanPoll::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t MonSpanPoll::lengthImpl() const
{
    return m_pImpl->length();
}

bool MonSpanPoll::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_ublox

} // namespace cc_tools_qt_plugin
