// Generated by commsdsl2tools_qt v6.3.2

#include "NavDgpsPoll.h"

#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_ublox/options/DefaultOptions.h"
#include "cc_ublox/message/NavDgpsPoll.h"

namespace cc_tools_qt_plugin
{

namespace cc_ublox
{

namespace message
{

namespace
{

QVariantList createProps()
{
    QVariantList props;
    return props;
}

} // namespace

class NavDgpsPollImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_ublox::message::NavDgpsPoll<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>,
        NavDgpsPollImpl
    >
{
public:
    NavDgpsPollImpl() = default;
    NavDgpsPollImpl(const NavDgpsPollImpl&) = delete;
    NavDgpsPollImpl(NavDgpsPollImpl&&) = delete;
    virtual ~NavDgpsPollImpl() = default;
    NavDgpsPollImpl& operator=(const NavDgpsPollImpl&) = default;
    NavDgpsPollImpl& operator=(NavDgpsPollImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

NavDgpsPoll::NavDgpsPoll() : m_pImpl(new NavDgpsPollImpl) {}
NavDgpsPoll::~NavDgpsPoll() = default;

NavDgpsPoll& NavDgpsPoll::operator=(const NavDgpsPoll& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

NavDgpsPoll& NavDgpsPoll::operator=(NavDgpsPoll&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

NavDgpsPoll::MsgIdParamType NavDgpsPoll::doGetId()
{
    return ::cc_ublox::message::NavDgpsPoll<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::doGetId();
}

const char* NavDgpsPoll::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& NavDgpsPoll::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void NavDgpsPoll::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void NavDgpsPoll::resetImpl()
{
    m_pImpl->reset();
}

bool NavDgpsPoll::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const NavDgpsPoll*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

NavDgpsPoll::MsgIdParamType NavDgpsPoll::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus NavDgpsPoll::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus NavDgpsPoll::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool NavDgpsPoll::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t NavDgpsPoll::lengthImpl() const
{
    return m_pImpl->length();
}

bool NavDgpsPoll::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_ublox

} // namespace cc_tools_qt_plugin
