// Generated by commsdsl2tools_qt v6.3.0

#include "NavTimegps.h"

#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_ublox/field/Ftow.h"
#include "cc_tools_qt_plugin/cc_ublox/field/Itow.h"
#include "cc_tools_qt_plugin/cc_ublox/options/DefaultOptions.h"
#include "cc_ublox/message/NavTimegps.h"

namespace cc_tools_qt_plugin
{

namespace cc_ublox
{

namespace message
{

namespace
{

static QVariantMap createProps_itow(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::NavTimegpsFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Itow;
    auto props = cc_tools_qt_plugin::cc_ublox::field::createProps_itow(Field::name(), serHidden);
    return props;
}

static QVariantMap createProps_ftow(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::NavTimegpsFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Ftow;
    auto props = cc_tools_qt_plugin::cc_ublox::field::createProps_ftow(Field::name(), serHidden);
    return props;
}

static QVariantMap createProps_weeks(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::NavTimegpsFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Weeks;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .asMap();
}

static QVariantMap createProps_leapS(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::NavTimegpsFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::LeapS;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .asMap();
}

static QVariantMap createProps_valid(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::NavTimegpsFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Valid;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .add(0U, "towValid")
            .add(1U, "weekValid")
            .add(2U, "leapSValid")
            .asMap();
}

static QVariantMap createProps_tAcc(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::NavTimegpsFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::TAcc;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .asMap();
}

QVariantList createProps()
{
    QVariantList props;
    props.append(createProps_itow(false));
    props.append(createProps_ftow(false));
    props.append(createProps_weeks(false));
    props.append(createProps_leapS(false));
    props.append(createProps_valid(false));
    props.append(createProps_tAcc(false));
    return props;
}

} // namespace

class NavTimegpsImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_ublox::message::NavTimegps<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>,
        NavTimegpsImpl
    >
{
public:
    NavTimegpsImpl() = default;
    NavTimegpsImpl(const NavTimegpsImpl&) = delete;
    NavTimegpsImpl(NavTimegpsImpl&&) = delete;
    virtual ~NavTimegpsImpl() = default;
    NavTimegpsImpl& operator=(const NavTimegpsImpl&) = default;
    NavTimegpsImpl& operator=(NavTimegpsImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

NavTimegps::NavTimegps() : m_pImpl(new NavTimegpsImpl) {}
NavTimegps::~NavTimegps() = default;

NavTimegps& NavTimegps::operator=(const NavTimegps& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

NavTimegps& NavTimegps::operator=(NavTimegps&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

NavTimegps::MsgIdParamType NavTimegps::doGetId()
{
    return ::cc_ublox::message::NavTimegps<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::doGetId();
}

const char* NavTimegps::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& NavTimegps::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void NavTimegps::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void NavTimegps::resetImpl()
{
    m_pImpl->reset();
}

bool NavTimegps::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const NavTimegps*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

NavTimegps::MsgIdParamType NavTimegps::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus NavTimegps::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus NavTimegps::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool NavTimegps::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t NavTimegps::lengthImpl() const
{
    return m_pImpl->length();
}

bool NavTimegps::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_ublox

} // namespace cc_tools_qt_plugin
