// Generated by commsdsl2tools_qt v6.3.4

#include "RxmPmreq.h"

#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_ublox/options/DefaultOptions.h"
#include "cc_ublox/message/RxmPmreq.h"

namespace cc_tools_qt_plugin
{

namespace cc_ublox
{

namespace message
{

namespace
{

static QVariantMap createProps_duration(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::RxmPmreqFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Duration;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .asMap();
}

static QVariantMap createProps_flags(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::RxmPmreqFields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Flags;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .add(1U, "backup")
            .asMap();
}

QVariantList createProps()
{
    QVariantList props;
    props.append(createProps_duration(false));
    props.append(createProps_flags(false));
    return props;
}

} // namespace

class RxmPmreqImpl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_ublox::message::RxmPmreq<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>,
        RxmPmreqImpl
    >
{
public:
    RxmPmreqImpl() = default;
    RxmPmreqImpl(const RxmPmreqImpl&) = delete;
    RxmPmreqImpl(RxmPmreqImpl&&) = delete;
    virtual ~RxmPmreqImpl() = default;
    RxmPmreqImpl& operator=(const RxmPmreqImpl&) = default;
    RxmPmreqImpl& operator=(RxmPmreqImpl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

RxmPmreq::RxmPmreq() : m_pImpl(new RxmPmreqImpl) {}
RxmPmreq::~RxmPmreq() = default;

RxmPmreq& RxmPmreq::operator=(const RxmPmreq& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

RxmPmreq& RxmPmreq::operator=(RxmPmreq&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

RxmPmreq::MsgIdParamType RxmPmreq::doGetId()
{
    return ::cc_ublox::message::RxmPmreq<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::doGetId();
}

const char* RxmPmreq::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& RxmPmreq::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void RxmPmreq::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void RxmPmreq::resetImpl()
{
    m_pImpl->reset();
}

bool RxmPmreq::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const RxmPmreq*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

RxmPmreq::MsgIdParamType RxmPmreq::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus RxmPmreq::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus RxmPmreq::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool RxmPmreq::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t RxmPmreq::lengthImpl() const
{
    return m_pImpl->length();
}

bool RxmPmreq::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_ublox

} // namespace cc_tools_qt_plugin
