// Generated by commsdsl2tools_qt v6.3.4

#include "RxmPmreqV0.h"

#include "cc_tools_qt/ProtocolMessageBase.h"
#include "cc_tools_qt/property/field.h"
#include "cc_tools_qt_plugin/cc_ublox/field/Res3.h"
#include "cc_tools_qt_plugin/cc_ublox/options/DefaultOptions.h"
#include "cc_ublox/message/RxmPmreqV0.h"

namespace cc_tools_qt_plugin
{

namespace cc_ublox
{

namespace message
{

namespace
{

static QVariantMap createProps_version(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::RxmPmreqV0Fields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Version;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .readOnly()
            .asMap();
}

static QVariantMap createProps_reserved1(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::RxmPmreqV0Fields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Reserved1;
    auto props = cc_tools_qt_plugin::cc_ublox::field::createProps_res3(Field::name(), serHidden);
    return props;
}

static QVariantMap createProps_duration(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::RxmPmreqV0Fields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Duration;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .asMap();
}

static QVariantMap createProps_flags(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::RxmPmreqV0Fields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::Flags;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .add(1U, "backup")
            .add(2U, "force")
            .asMap();
}

static QVariantMap createProps_wakeupSources(bool serHidden)
{
    static_cast<void>(serHidden);
    using Field = ::cc_ublox::message::RxmPmreqV0Fields<cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::WakeupSources;
    return
        cc_tools_qt::property::field::ForField<Field>()
            .name(Field::name())
            .serialisedHidden(serHidden)
            .add(3U, "uartrx")
            .add(5U, "extint0")
            .add(6U, "extint1")
            .add(7U, "spics")
            .asMap();
}

QVariantList createProps()
{
    QVariantList props;
    props.append(createProps_version(false));
    props.append(createProps_reserved1(false));
    props.append(createProps_duration(false));
    props.append(createProps_flags(false));
    props.append(createProps_wakeupSources(false));
    return props;
}

} // namespace

class RxmPmreqV0Impl : public
    cc_tools_qt::ProtocolMessageBase<
        ::cc_ublox::message::RxmPmreqV0<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>,
        RxmPmreqV0Impl
    >
{
public:
    RxmPmreqV0Impl() = default;
    RxmPmreqV0Impl(const RxmPmreqV0Impl&) = delete;
    RxmPmreqV0Impl(RxmPmreqV0Impl&&) = delete;
    virtual ~RxmPmreqV0Impl() = default;
    RxmPmreqV0Impl& operator=(const RxmPmreqV0Impl&) = default;
    RxmPmreqV0Impl& operator=(RxmPmreqV0Impl&&) = default;

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override
    {
        static const QVariantList Props = createProps();
        return Props;
    }
};

RxmPmreqV0::RxmPmreqV0() : m_pImpl(new RxmPmreqV0Impl) {}
RxmPmreqV0::~RxmPmreqV0() = default;

RxmPmreqV0& RxmPmreqV0::operator=(const RxmPmreqV0& other)
{
    *m_pImpl = *other.m_pImpl;
    return *this;
}

RxmPmreqV0& RxmPmreqV0::operator=(RxmPmreqV0&& other)
{
    *m_pImpl = std::move(*other.m_pImpl);
    return *this;
}

RxmPmreqV0::MsgIdParamType RxmPmreqV0::doGetId()
{
    return ::cc_ublox::message::RxmPmreqV0<cc_tools_qt_plugin::cc_ublox::Message, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>::doGetId();
}

const char* RxmPmreqV0::nameImpl() const
{
    return static_cast<const cc_tools_qt::Message*>(m_pImpl.get())->name();
}

const QVariantList& RxmPmreqV0::fieldsPropertiesImpl() const
{
    return m_pImpl->fieldsProperties();
}

void RxmPmreqV0::dispatchImpl(cc_tools_qt::MessageHandler& handler)
{
    static_cast<cc_tools_qt::Message*>(m_pImpl.get())->dispatch(handler);
}

void RxmPmreqV0::resetImpl()
{
    m_pImpl->reset();
}

bool RxmPmreqV0::assignImpl(const cc_tools_qt::Message& other)
{
    auto* castedOther = dynamic_cast<const RxmPmreqV0*>(&other);
    if (castedOther == nullptr) {
        return false;
    }
    return m_pImpl->assign(*castedOther->m_pImpl);
}

RxmPmreqV0::MsgIdParamType RxmPmreqV0::getIdImpl() const
{
    return m_pImpl->getId();
}

comms::ErrorStatus RxmPmreqV0::readImpl(ReadIterator& iter, std::size_t len)
{
    return m_pImpl->read(iter, len);
}

comms::ErrorStatus RxmPmreqV0::writeImpl(WriteIterator& iter, std::size_t len) const
{
    return m_pImpl->write(iter, len);
}

bool RxmPmreqV0::validImpl() const
{
    return m_pImpl->valid();
}

std::size_t RxmPmreqV0::lengthImpl() const
{
    return m_pImpl->length();
}

bool RxmPmreqV0::refreshImpl()
{
    return m_pImpl->refresh();
}

} // namespace message

} // namespace cc_ublox

} // namespace cc_tools_qt_plugin
