// Generated by commsdsl2tools_qt v6.3.3

#pragma once

#include "cc_tools_qt/version.h"

static_assert(CC_TOOLS_QT_MAKE_VERSION(5, 3, 1) <= cc_tools_qt::version(),
    "The version of cc_tools_qt library is too old");
