// Generated by commsdsl2tools_qt v7.3.0

#include "UbloxFrame.h"

#include "cc_tools_qt/ToolsFrameBase.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/Message.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/factory/MsgFactory.h"
#include "cc_tools_qt_plugin/Message/cc_ublox/frame/UbloxFrameTransportMessage.h"
#include "cc_tools_qt_plugin/cc_ublox/Version.h"
#include "cc_tools_qt_plugin/cc_ublox/options/DefaultOptions.h"
#include "cc_ublox/frame/UbloxFrame.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_ublox
{

namespace frame
{

namespace
{
using ProtUbloxFrame =
    ::cc_ublox::frame::UbloxFrame<
        cc_tools_qt_plugin::Message::cc_ublox::Message::ProtInterface,
        ::cc_ublox::input::AllMessages<cc_tools_qt_plugin::Message::cc_ublox::Message::ProtInterface, cc_tools_qt_plugin::cc_ublox::options::DefaultOptions>,
        cc_tools_qt_plugin::cc_ublox::options::DefaultOptions
     >;
}// namespace

class UbloxFrameImpl : public
   cc_tools_qt::ToolsFrameBase<
       cc_tools_qt_plugin::Message::cc_ublox::Message,
       ProtUbloxFrame,
       cc_tools_qt_plugin::Message::cc_ublox::factory::MsgFactory,
       cc_tools_qt_plugin::Message::cc_ublox::frame::UbloxFrameTransportMessage
   >
{
};

UbloxFrame::UbloxFrame() :
    m_pImpl(new UbloxFrameImpl){
}

UbloxFrame::~UbloxFrame() = default;

cc_tools_qt::ToolsMessagesList UbloxFrame::readDataImpl(const cc_tools_qt::ToolsDataInfo& dataInfo, bool final)
{
    return m_pImpl->readData(dataInfo, final);
}

void UbloxFrame::updateMessageImpl(cc_tools_qt::ToolsMessage& msg)
{
    return m_pImpl->updateMessage(msg);
}

cc_tools_qt::ToolsMessagePtr UbloxFrame::createInvalidMessageImpl()
{
    return m_pImpl->createInvalidMessage();
}

cc_tools_qt::ToolsMessagePtr UbloxFrame::createRawDataMessageImpl()
{
    return m_pImpl->createRawDataMessage();
}

cc_tools_qt::ToolsMessagePtr UbloxFrame::createExtraInfoMessageImpl()
{
    return m_pImpl->createExtraInfoMessage();
}

cc_tools_qt::ToolsMessagesList UbloxFrame::createAllMessagesImpl()
{
    return m_pImpl->createAllMessages();
}

cc_tools_qt::ToolsMessagePtr UbloxFrame::createMessageImpl(const QString& idAsString, unsigned idx)
{
    return m_pImpl->createMessage(idAsString, idx);
}

UbloxFrame::DataSeq UbloxFrame::writeProtMsgImpl(const void* protInterface)
{
    return m_pImpl->writeProtMsg(protInterface);
}

} // namespace frame

} // namespace cc_ublox

} // namespace Message

} // namespace cc_tools_qt_plugin
