// Generated by commsdsl2tools_qt v8.0.0

#pragma once

#include <tuple>
#include "cc_tools_qt/ToolsTransportProtMessageBase.h"
#include "cc_ublox/frame/UbloxFrame.h"

namespace cc_tools_qt_plugin
{

namespace Message
{

namespace cc_ublox
{

namespace frame
{

template <typename TOpt>
struct UbloxFrameProtTransportMessageFields
{
    using All =
        std::tuple<
            typename ::cc_ublox::frame::UbloxFrameLayers<TOpt>::SyncMembers::Sync,
            typename ::cc_ublox::frame::UbloxFrameLayers<TOpt>::IdMembers::MsgId,
            typename ::cc_ublox::frame::UbloxFrameLayers<TOpt>::LengthMembers::LENGTH,
            typename ::cc_ublox::frame::UbloxFrameLayers<TOpt>::Payload::Field,
            typename ::cc_ublox::frame::UbloxFrameLayers<TOpt>::ChecksumMembers::Checksum
        >;
};

template <typename TMsgBase, typename TOpt>
class UbloxFrameProtTransportMessage : public
    cc_tools_qt::ToolsTransportProtMessageBase<
        TMsgBase,
        typename UbloxFrameProtTransportMessageFields<TOpt>::All,
        UbloxFrameProtTransportMessage<TMsgBase, TOpt>
    >
{
    using Base =
        cc_tools_qt::ToolsTransportProtMessageBase<
            TMsgBase,
            typename UbloxFrameProtTransportMessageFields<TOpt>::All,
            UbloxFrameProtTransportMessage<TMsgBase, TOpt>
        >;
public:
    COMMS_MSG_FIELDS_NAMES(
        sync,
        id,
        length,
        payload,
        checksum
    );

    template <typename TIter>
    comms::ErrorStatus doRead(TIter& iter, std::size_t len)
    {
        len -= 2;
        auto es = Base::template doReadUntilAndUpdateLen<4>(iter, len);
        if (es == comms::ErrorStatus::Success) {
            len += 2;
            es = Base::template doReadFrom<4>(iter, len);
        }

        return es;
    }
};

} // namespace frame

} // namespace cc_ublox

} // namespace Message

} // namespace cc_tools_qt_plugin
