// Generated by commsdsl2tools_qt v6.3.0

/// @file
/// @brief Contains definition of the options for framing which force usage of message factory.

#pragma once

#include "cc_tools_qt_plugin/cc_ublox/factory/AllMessagesDynMemMsgFactory.h"
#include "cc_tools_qt_plugin/cc_ublox/options/DefaultOptions.h"

namespace cc_tools_qt_plugin
{

namespace cc_ublox
{

namespace options
{

struct MsgFactoryFrameOptions : public cc_tools_qt_plugin::cc_ublox::options::DefaultOptions
{
    template <typename TInterface, typename TAllMessages, typename... TOptions>
    using MsgFactory = cc_tools_qt_plugin::cc_ublox::factory::AllMessagesDynMemMsgFactory;

    struct frame : public cc_tools_qt_plugin::cc_ublox::options::DefaultOptions::frame
    {
        struct UbloxFrameLayers : public cc_tools_qt_plugin::cc_ublox::options::DefaultOptions::frame::UbloxFrameLayers
        {
            using Id =
                std::tuple<
                    comms::option::app::MsgFactoryTempl<MsgFactory>,
                    typename cc_tools_qt_plugin::cc_ublox::options::DefaultOptions::frame::UbloxFrameLayers::Id
                >;
        }; // struct UbloxFrameLayers
    }; // struct frame
};

} // namespace options

} // namespace cc_ublox

} // namespace cc_tools_qt_plugin
